INSERT INTO "toefl" VALUES(1,'throughout','遍部','They export their products to markets throughout the world.');
INSERT INTO "toefl" VALUES(2,'navigational','領航的','A navigational aid is any sort of marker which aids the traveler in navigation.');
INSERT INTO "toefl" VALUES(3,'carbonated','碳酸的','carbonated drinks.');
INSERT INTO "toefl" VALUES(4,'flood','大量','a flood of complaints.');
INSERT INTO "toefl" VALUES(5,'demonstrate','說明','Let me demonstrate to you some of the difficulties we are facing.');
INSERT INTO "toefl" VALUES(6,'accountant','會計師','An accountant is a practitioner of accountancy or accounting.');
INSERT INTO "toefl" VALUES(7,'above','高於','The water came above our knees.');
INSERT INTO "toefl" VALUES(8,'fame','名譽','The town''s only claim to fame is that there was once a riot there.');
INSERT INTO "toefl" VALUES(9,'diverse','多樣的','My interests are very diverse.');
INSERT INTO "toefl" VALUES(10,'moist','潮濕的','Water the plants regularly to keep the soil moist.');
INSERT INTO "toefl" VALUES(11,'permanent','永久的','The accident has not done any permanent damage.');
INSERT INTO "toefl" VALUES(12,'vapor','蒸氣','water vapour');
INSERT INTO "toefl" VALUES(13,'petroleum','石油','Crude oil, also known as petroleum , is the world''s most actively traded commodity.');
INSERT INTO "toefl" VALUES(14,'electricity','電力','The electricity is off.');
INSERT INTO "toefl" VALUES(15,'fertile','肥沃的','Fertile soil in a sunny site.');
INSERT INTO "toefl" VALUES(16,'accumulate','累積','I seem to have accumulated a lot of books.');
INSERT INTO "toefl" VALUES(17,'brief','短暫的','Mozart''s life was brief.');
INSERT INTO "toefl" VALUES(18,'innovate','創新','We must constantly adapt and innovate to ensure success in a growing market.');
INSERT INTO "toefl" VALUES(19,'Inuit','因紐特人','A race of people from northern Canada and parts of Greenland and Alaska.');
INSERT INTO "toefl" VALUES(20,'internal','內部的','The medicine is not for internal use.');
INSERT INTO "toefl" VALUES(21,'watercolor','水彩畫','Watercolor on paper.');
INSERT INTO "toefl" VALUES(22,'transfer','轉移','How can I transfer money from my bank account to his?');
INSERT INTO "toefl" VALUES(23,'deposit','抵押金','They normally ask you to pay $100 (as a) deposit.');
INSERT INTO "toefl" VALUES(24,'pastor','牧師','NULL');
INSERT INTO "toefl" VALUES(25,'skeleton','骨架','The human skeleton consists of 206 bones.');
INSERT INTO "toefl" VALUES(26,'marine','海洋的','marine life');
INSERT INTO "toefl" VALUES(27,'divide','劃分','A sentence can be divided up into meaningful segments.');
INSERT INTO "toefl" VALUES(28,'basin','盆地','The entire Amazon basin  contains the largest number of freshwater fish . ');
INSERT INTO "toefl" VALUES(29,'distract','使分心','You''re distracting me from my work.');
INSERT INTO "toefl" VALUES(30,'aware','察覺','As you''re aware, this is not a new problem.');
INSERT INTO "toefl" VALUES(31,'ceremony','典禮','a marriage ceremony. ');
INSERT INTO "toefl" VALUES(32,'dioxide','二氧化','NULL');
INSERT INTO "toefl" VALUES(33,'dominant','支配的','The firm has achieved a dominant position in the world market.');
INSERT INTO "toefl" VALUES(34,'oxygen','氧氣','NULL');
INSERT INTO "toefl" VALUES(35,'dolphin','海豚','NULL');
INSERT INTO "toefl" VALUES(36,'tropical','熱帶的','tropical fish');
INSERT INTO "toefl" VALUES(37,'inhabit','居住在','Small animals inhabited the woods. ');
INSERT INTO "toefl" VALUES(38,'particle','粒子','NULL');
INSERT INTO "toefl" VALUES(39,'colloquial','口語的','In these cases, if you add an up, it makes your sentence more colloquial, more informal.');
INSERT INTO "toefl" VALUES(40,'asteroid','小行星','It''s just that you can't keep quiet about things like asteroid impacts.');
INSERT INTO "toefl" VALUES(41,'marsupial','有袋動物','Kangaroos and koalas are marsupials.');
INSERT INTO "toefl" VALUES(42,'cretaceous','白堊紀','NULL');
INSERT INTO "toefl" VALUES(43,'shrub','灌木','Hundreds of trees and shrubs will be planted at Croome Park during December.');
INSERT INTO "toefl" VALUES(44,'grain','糧食','The food grain was first domesticated over 10,000 years ago in the Middle East.');
INSERT INTO "toefl" VALUES(45,'vertebrate','脊椎動物','NULL');
INSERT INTO "toefl" VALUES(46,'Mediterranean','地中海','NULL');
INSERT INTO "toefl" VALUES(47,'Celsius','攝氏','It will be a mild night, around nine degrees Celsius.');
INSERT INTO "toefl" VALUES(48,'maize','玉米','NULL');
INSERT INTO "toefl" VALUES(49,'philosophy','哲學','NULL');
INSERT INTO "toefl" VALUES(50,'enlist','招募','We were enlisted as helpers.');
INSERT INTO "toefl" VALUES(51,'bacterium','細菌','NULL');
INSERT INTO "toefl" VALUES(52,'distinguish',' 分辨','It was hard to distinguish one twin from the other.');
INSERT INTO "toefl" VALUES(53,'pine','松','NULL');
INSERT INTO "toefl" VALUES(54,'interact','互動','The only thing he interacts with is his computer!');
INSERT INTO "toefl" VALUES(55,'due','到期的','Payment is due on 1 October.');
INSERT INTO "toefl" VALUES(56,'aquifer','含水層','NULL');
INSERT INTO "toefl" VALUES(57,'paradigm','典範','The war was a paradigm of the destructive side of human nature.');
INSERT INTO "toefl" VALUES(58,'domestic','賢慧的','I''m not a very domestic sort of person.');
INSERT INTO "toefl" VALUES(59,'phenomenon','現象','Globalization is a phenomenon of the 21st century.');
INSERT INTO "toefl" VALUES(60,'frontal','正面的','Airbags protect the driver in the event of a severe frontal impact.');
INSERT INTO "toefl" VALUES(61,'ceramic','陶瓷的','Clay or ceramic pots are the best choice for cacti.');
INSERT INTO "toefl" VALUES(62,'orient','導向','Lectures designed to orient the new students. ');
INSERT INTO "toefl" VALUES(63,'scholar','學者','He was the most distinguished scholar in his field.');
INSERT INTO "toefl" VALUES(64,'classify','歸類','Would you classify it as a hard drug or a soft drug?');
INSERT INTO "toefl" VALUES(65,'irrigate','灌溉','The water helps irrigate 14,000 hectares or 35,000 acres of cotton.');
INSERT INTO "toefl" VALUES(66,'administrate','管理','We administrate and manage our daily affairs and our social relations.');
INSERT INTO "toefl" VALUES(67,'cognitive','認知的','a child''s cognitive development');
INSERT INTO "toefl" VALUES(68,'pigeon','鴿子','NULL');
INSERT INTO "toefl" VALUES(69,'mate','夥伴','They''ve been best mates since school.');
INSERT INTO "toefl" VALUES(70,'elite','有權者','In these countries, only the elite can afford an education for their children.');
INSERT INTO "toefl" VALUES(71,'Mesoamerica','中美洲','NULL');
INSERT INTO "toefl" VALUES(72,'wing','翼側','There was a dent in the nearside wing.');
INSERT INTO "toefl" VALUES(73,'climax','精采的部分','The book''s powerful climax is the murder of Nancy by her lover Bill Sikes.');
INSERT INTO "toefl" VALUES(74,'trait','特徵','Awareness of class is a typically British trait.');
INSERT INTO "toefl" VALUES(75,'bark','樹皮','The sharp edges of the bark cut my hands in several places.');
INSERT INTO "toefl" VALUES(76,'Paleolithic','舊石器時代','It''s true that evolution didn't stop in the Paleolithic.');
INSERT INTO "toefl" VALUES(77,'content','主旨','The content of the course depends on what the students would like to study.');
INSERT INTO "toefl" VALUES(78,'appreciable','大量','The increase in salary will be appreciable.');
INSERT INTO "toefl" VALUES(79,'radiation','輻射','the treatment of cancer and other diseases using radiation');
INSERT INTO "toefl" VALUES(80,'timescale','時程','We hope the negotiations will be completed within a six-month timescale.');
INSERT INTO "toefl" VALUES(81,'toad','蟾蜍','NULL');
INSERT INTO "toefl" VALUES(82,'tulip','鬱金香','NULL');
INSERT INTO "toefl" VALUES(83,'depict','描繪','The artist had depicted her lying on a bed.');
INSERT INTO "toefl" VALUES(84,'rhythm','韻律','The boat rocked up and down in rhythm with the sea.');
INSERT INTO "toefl" VALUES(85,'substance','(化學)物質','a sticky substance');
INSERT INTO "toefl" VALUES(86,'acid','酸',' His criticism was pure acid. ');
INSERT INTO "toefl" VALUES(87,'haven','避難所','The river banks are a haven for wildlife.');
INSERT INTO "toefl" VALUES(88,'breed','繁殖','Many animals breed only at certain times of the year.');
INSERT INTO "toefl" VALUES(89,'Arctic','北極的','Arctic explorers');
INSERT INTO "toefl" VALUES(90,'crust','地殼','the earth''s crust');
INSERT INTO "toefl" VALUES(91,'offspring','後代','Female badgers may give birth to as many as five offspring.');
INSERT INTO "toefl" VALUES(92,'equate','畫上等號','Some parents equate education with exam success.');
INSERT INTO "toefl" VALUES(93,'mercury','水銀','Mercury is a poisonous silver liquid metal.');
INSERT INTO "toefl" VALUES(94,'drought','乾旱','The country''s entire grain harvest has been hit by drought.');
INSERT INTO "toefl" VALUES(95,'chimpanzee','黑猩猩','NULL');
INSERT INTO "toefl" VALUES(96,'portrait','肖像','He had his portrait painted in uniform.');
INSERT INTO "toefl" VALUES(97,'reptile','爬蟲類','NULL');
INSERT INTO "toefl" VALUES(98,'forage','覓食','The female only leaves the young when she forages for food.');
INSERT INTO "toefl" VALUES(99,'ritual','儀式','She objects to the ritual of organized religion.');
INSERT INTO "toefl" VALUES(100,'screen','遮蔽','Dark glasses screened his eyes from the sun.');
INSERT INTO "toefl" VALUES(101,'resemble','相似','She closely resembles her sister.');
INSERT INTO "toefl" VALUES(102,'inborn','天生的','Some people have an inborn tendency to put on weight.');
INSERT INTO "toefl" VALUES(103,'wearing','使勞累的','It''s been a very wearing day.');
INSERT INTO "toefl" VALUES(104,'algae','海藻','NULL');
INSERT INTO "toefl" VALUES(105,'conscious','有意識的','A patient who is not fully conscious should never be left alone.');
INSERT INTO "toefl" VALUES(106,'crater','坑洞','a meteorite crater');
INSERT INTO "toefl" VALUES(107,'stencil','印刷模板','NULL');
INSERT INTO "toefl" VALUES(108,'epoch','時期','The death of the emperor marked the end of an epoch in the country''s history.');
INSERT INTO "toefl" VALUES(109,'nectar','花蜜','On such a hot day, even water was nectar ');
INSERT INTO "toefl" VALUES(110,'sophisticated','老於世故的','Mark is a smart and sophisticated young man.');
INSERT INTO "toefl" VALUES(111,'ancestor','祖先','His ancestors had come to America from Ireland.');
INSERT INTO "toefl" VALUES(112,'metamorphosis','變質','She had undergone an amazing metamorphosis from awkward schoolgirl to beautiful woman.');
INSERT INTO "toefl" VALUES(113,'craft','手製','All the furniture is crafted from natural materials.');
INSERT INTO "toefl" VALUES(114,'pore','毛孔','NULL');
INSERT INTO "toefl" VALUES(115,'flat','平淡的','Her voice was flat and expressionless.');
INSERT INTO "toefl" VALUES(116,'pigment','色素','Haemoglobin is the red pigment found in blood.');
INSERT INTO "toefl" VALUES(117,'exploit','利用','He exploited his father''s name to get himself a job.');
INSERT INTO "toefl" VALUES(118,'Darwin','達爾文','NULL');
INSERT INTO "toefl" VALUES(119,'dissolve','去除','a new detergent that dissolves stains');
INSERT INTO "toefl" VALUES(120,'contemporary','同時代的','He was contemporary with the dramatist Congreve.');
INSERT INTO "toefl" VALUES(121,'inspire','激發','His superb play inspired the team to a thrilling 5–0 win.');
INSERT INTO "toefl" VALUES(122,'court','法庭','He won the court case and was awarded damages.');
INSERT INTO "toefl" VALUES(123,'fiber','纖維','He has been advised to increase his fibre intake.');
INSERT INTO "toefl" VALUES(124,'humid','潮濕的','The island is hot and humid in the summer.');
INSERT INTO "toefl" VALUES(125,'imitate','模仿','Her style of painting has been imitated by other artists.');
INSERT INTO "toefl" VALUES(126,'contaminate','汙染','The drinking water has become contaminated with lead.');
INSERT INTO "toefl" VALUES(127,'context','來龍去脈','This speech needs to be set in the context of Britain in the 1960s.');
INSERT INTO "toefl" VALUES(128,'obsidian','黑曜岩','NULL');
INSERT INTO "toefl" VALUES(129,'cultivate','耕種','The people cultivate mainly rice and beans.');
INSERT INTO "toefl" VALUES(130,'Cambrian','寒武紀','NULL');
INSERT INTO "toefl" VALUES(131,'drain','抽乾','The marshes have been drained.');
INSERT INTO "toefl" VALUES(132,'somehow','不知怎搞得','Somehow, I don''t feel I can trust him.');
INSERT INTO "toefl" VALUES(133,'somewhat','一點地','The situation has changed somewhat since we last met.');
INSERT INTO "toefl" VALUES(134,'adequate','足夠的','The room was small but adequate.');
INSERT INTO "toefl" VALUES(135,'classic','經典的','She displayed the classic symptoms of depression.');
INSERT INTO "toefl" VALUES(136,'classical','古典','the classical theory of unemployment');
INSERT INTO "toefl" VALUES(137,'termite','白蟻','NULL');
INSERT INTO "toefl" VALUES(138,'rural','鄉村的','a rural way of life');
INSERT INTO "toefl" VALUES(139,'plus','"+"','Two plus five is seven.');
INSERT INTO "toefl" VALUES(140,'linguist','精通語言的人','She''s an excellent linguist.');
INSERT INTO "toefl" VALUES(141,'Atlantic','大西洋','NULL');
INSERT INTO "toefl" VALUES(142,'timber','木材','the timber industry');
INSERT INTO "toefl" VALUES(143,'evaporate','蒸發','Heat until all the water has evaporated.');
INSERT INTO "toefl" VALUES(144,'microscopic','只能從顯微鏡下看的','The sandwiches were microscopic!');
INSERT INTO "toefl" VALUES(145,'echo','回聲','There was an echo on the phone and I couldn''t hear clearly.');
INSERT INTO "toefl" VALUES(146,'engage','從事於','He is currently engaged as a consultant.');
INSERT INTO "toefl" VALUES(147,'excavate','挖掘','The site has been excavated by archaeologists.');
INSERT INTO "toefl" VALUES(148,'genre','流派','the genre of symphonic music. ');
INSERT INTO "toefl" VALUES(149,'perspective','透視的','We learnt how to draw buildings in perspective.');
INSERT INTO "toefl" VALUES(150,'pheromone','費洛蒙','NULL');
INSERT INTO "toefl" VALUES(151,'Neolithic','新石器時代','NULL');
INSERT INTO "toefl" VALUES(152,'dune','沙丘','NULL');
INSERT INTO "toefl" VALUES(153,'dispense','生產','The machine dispenses a range of drinks and snacks.');
INSERT INTO "toefl" VALUES(154,'Aristotle','亞里斯多德','NULL');
INSERT INTO "toefl" VALUES(155,'anthropology','人類學','NULL');
INSERT INTO "toefl" VALUES(156,'shallow','淺的','These fish are found in shallow waters around the coast.');
INSERT INTO "toefl" VALUES(157,'warbler','會唱歌的鳥','NULL');
INSERT INTO "toefl" VALUES(158,'moth','蛾','NULL');
INSERT INTO "toefl" VALUES(159,'arid','非常乾燥的','Nothing grows in these arid regions.');
INSERT INTO "toefl" VALUES(160,'probe','探測器','NULL');
INSERT INTO "toefl" VALUES(161,'hibernation','冬眠期','NULL');
INSERT INTO "toefl" VALUES(162,'first','創舉','notable firsts');
INSERT INTO "toefl" VALUES(163,'notch-up ','達成','The team has notched up 20 goals already this season.');
INSERT INTO "toefl" VALUES(164,'orbit','公轉','The earth takes a year to orbit the sun.');
INSERT INTO "toefl" VALUES(165,'line-up ','排隊','The suspects were lined up against the wall.');
INSERT INTO "toefl" VALUES(166,'hieroglyph','象形文字','NULL');
INSERT INTO "toefl" VALUES(167,'deploy ','部屬','we also deploy the lander to probe the surface of the comet.');
INSERT INTO "toefl" VALUES(168,'pristine','安靜的','The car is in pristine condition.');
INSERT INTO "toefl" VALUES(169,'building-blocks ','積木','building blocks of life ');
INSERT INTO "toefl" VALUES(170,'unwitting ','不知情','unwitting customers');
INSERT INTO "toefl" VALUES(171,'solitary ','獨自一人的','Mink live solitary lives.');
INSERT INTO "toefl" VALUES(172,'inquisitive ','好奇心旺盛的','Don''t be so inquisitive');
INSERT INTO "toefl" VALUES(173,'otter','水獺','NULL');
INSERT INTO "toefl" VALUES(174,'consensus ','共識','There is a growing consensus of opinion on this issue.');
INSERT INTO "toefl" VALUES(175,'temperate','溫帶','temperate tree species');
INSERT INTO "toefl" VALUES(176,'mass','質量','NULL');
INSERT INTO "toefl" VALUES(177,'senescence','衰老',' plant senescence');
INSERT INTO "toefl" VALUES(178,'gruesome','毛骨悚然的','gruesome photos ');
INSERT INTO "toefl" VALUES(179,'renown','名聲','NULL');
INSERT INTO "toefl" VALUES(180,'prosecutor','檢察官','NULL');
INSERT INTO "toefl" VALUES(181,'alleged','據稱的','The girl gave evidence in court against her alleged attacker.');
INSERT INTO "toefl" VALUES(182,'garnish','配菜','a garnish of tomato');
INSERT INTO "toefl" VALUES(183,'sulfur','硫磺','NULL');
INSERT INTO "toefl" VALUES(184,'paleontology','古生物學','NULL');
INSERT INTO "toefl" VALUES(185,'still-life ','寫生','She prefers still life to landscape painting.');
INSERT INTO "toefl" VALUES(186,'derive','獲得','He derived great pleasure from painting.');
INSERT INTO "toefl" VALUES(187,'dialect','方言','NULL');
INSERT INTO "toefl" VALUES(188,'exaggerate','誇大','He tends to exaggerate the difficulties.');
INSERT INTO "toefl" VALUES(189,'prairie','大草原','NULL');
INSERT INTO "toefl" VALUES(190,'cereal','穀物','NULL');
INSERT INTO "toefl" VALUES(191,'hippopotamus','河馬','NULL');
INSERT INTO "toefl" VALUES(192,'amnesia','失憶症','This new discovery helps amnesiacs keep their memory.');
INSERT INTO "toefl" VALUES(193,'dynasty','朝代','a Ming dynasty vase');
INSERT INTO "toefl" VALUES(194,'vital','重要的','Good financial accounts are vital to the success of any enterprise.');
INSERT INTO "toefl" VALUES(195,'mere','僅僅','A mere 2% of their budget has been spent on publicity.');
INSERT INTO "toefl" VALUES(196,'luxuriant','茂盛的','luxuriant vegetation');
INSERT INTO "toefl" VALUES(197,'cape','海角','Cape Horn');
INSERT INTO "toefl" VALUES(198,'nitrogen','氮','NULL');
INSERT INTO "toefl" VALUES(199,'aesthetic ','美學的','Their furniture was more aesthetic than functional.');
INSERT INTO "toefl" VALUES(200,'medieval','中古世紀','the literature of the late medieval period');
INSERT INTO "toefl" VALUES(201,'whereas','而','Some of the studies show positive results, whereas others do not.');
INSERT INTO "toefl" VALUES(202,'chamber ','房間','Divers transfer from the water to a decompression chamber.');
INSERT INTO "toefl" VALUES(203,'gravel','砂礫','Put a layer of fine gravel into the bottom of the plant pot for drainage.');
INSERT INTO "toefl" VALUES(204,'precede','先前','She preceded me in the job.');
INSERT INTO "toefl" VALUES(205,'limestone','石灰岩','NULL');
INSERT INTO "toefl" VALUES(206,'Shakespeare','莎士比亞','NULL');
INSERT INTO "toefl" VALUES(207,'disperse','消散','The fog began to disperse.');
INSERT INTO "toefl" VALUES(208,'tundra','苔原','NULL');
INSERT INTO "toefl" VALUES(209,'monument','紀念碑','A monument to him was erected in St Paul''s Cathedral.');
INSERT INTO "toefl" VALUES(210,'plow','犁','NULL');
INSERT INTO "toefl" VALUES(211,'cod','鱈魚','NULL');
INSERT INTO "toefl" VALUES(212,'inhibit','抑制','A lack of oxygen may inhibit brain development in the unborn child.');
INSERT INTO "toefl" VALUES(213,'permafrost','永凍土','NULL');
INSERT INTO "toefl" VALUES(214,'pharaoh','法老','NULL');
INSERT INTO "toefl" VALUES(215,'verbal','口頭的','The job applicant must have good verbal skills.');
INSERT INTO "toefl" VALUES(216,'saturate','浸濕','The continuous rain had saturated the soil.');
INSERT INTO "toefl" VALUES(217,'plankton','浮游生物','NULL');
INSERT INTO "toefl" VALUES(218,'ridge','山脊','We stood on the windswept ridge and looked down at the valley below.');
INSERT INTO "toefl" VALUES(219,'freshwater','淡水的','freshwater fish');
INSERT INTO "toefl" VALUES(220,'colossal','龐大','The singer earns a colossal amount of money.');
INSERT INTO "toefl" VALUES(221,'enroll','登記','You need to enrol before the end of August.');
INSERT INTO "toefl" VALUES(222,'pump','打水機','She washed her face at the pump in front of the inn.');
INSERT INTO "toefl" VALUES(223,'phosphorus','磷','NULL');
INSERT INTO "toefl" VALUES(224,'peninsula','半島','NULL');
INSERT INTO "toefl" VALUES(225,'deficient','不足的','a diet that is deficient in vitamin A');
INSERT INTO "toefl" VALUES(226,'herbivore','草食動物','NULL');
INSERT INTO "toefl" VALUES(227,'oblige','迫使','He suffered a serious injury that obliged him to give up work.');
INSERT INTO "toefl" VALUES(228,'harsh','刺耳的','He regretted his harsh words.');
INSERT INTO "toefl" VALUES(229,'Jupiter','木星','NULL');
INSERT INTO "toefl" VALUES(230,'flipper','蛙鞋','NULL');
INSERT INTO "toefl" VALUES(231,'deform','使畸形','The disease had deformed his spine.');
INSERT INTO "toefl" VALUES(232,'diffuse ','擴散','Technologies diffuse rapidly.');
INSERT INTO "toefl" VALUES(233,'topography','地形','a map showing the topography of the island');
INSERT INTO "toefl" VALUES(234,'porcelain','瓷器','The design is copied from Japanese porcelains of the fourteenth century.');
INSERT INTO "toefl" VALUES(235,'municipal','市政的','municipal workers');
INSERT INTO "toefl" VALUES(236,'swamp','沼澤','tropical swamps');
INSERT INTO "toefl" VALUES(237,'aim','達成',' They are aiming to reduce unemployment by 50%.');
INSERT INTO "toefl" VALUES(238,'flourish','茂盛','These plants flourish in a damp climate.');
INSERT INTO "toefl" VALUES(239,'larva','幼蟲','NULL');
INSERT INTO "toefl" VALUES(240,'enzyme','酵素','Enzymes are essential to the body''s functioning.');
INSERT INTO "toefl" VALUES(241,'niche','天職','He eventually found his niche in sports journalism.');
INSERT INTO "toefl" VALUES(242,'intrinsic','本質的','the intrinsic value of a gold ring. ');
INSERT INTO "toefl" VALUES(243,'millennium','一千年','For millennia, it was accepted that the earth was at the centre of the universe.');
INSERT INTO "toefl" VALUES(244,'ranch','大農場','NULL');
INSERT INTO "toefl" VALUES(245,'canyon','峽谷','NULL');
INSERT INTO "toefl" VALUES(246,'synthesis','合成','the synthesis of nucleic acids');
INSERT INTO "toefl" VALUES(247,'intrigue','使勾起興趣','You''ve really intrigued me—tell me more!');
INSERT INTO "toefl" VALUES(248,'transmit','傳送','The ceremony was transmitted live by satellite to over fifty countries.');
INSERT INTO "toefl" VALUES(249,'terrain','地帶','They walked for miles across steep and inhospitable terrain.');
INSERT INTO "toefl" VALUES(250,'predominant','顯著的','Yellow is the predominant colour this spring in the fashion world');
INSERT INTO "toefl" VALUES(251,'aristocracy','貴族','members of the aristocracy');
INSERT INTO "toefl" VALUES(252,'speculate','推測','We all speculated about the reasons for her resignation.');
INSERT INTO "toefl" VALUES(253,'inherit','繼承','She inherited a fortune from her father.');
INSERT INTO "toefl" VALUES(254,'exhaust','用光','Don''t give up until you have exhausted all the possibilities.');
INSERT INTO "toefl" VALUES(255,'attain','達到','Most of our students attained five ‘A’ grades in their exams.');
INSERT INTO "toefl" VALUES(256,'copper','銅','I only paid a few coppers for it.');
INSERT INTO "toefl" VALUES(257,'corridor','走廊','His room is along the corridor.');
INSERT INTO "toefl" VALUES(258,'insulate','隔絕','Home owners are being encouraged to insulate their homes to save energy.');
INSERT INTO "toefl" VALUES(259,'cinema','電影','I used to go to the cinema every week.');
INSERT INTO "toefl" VALUES(260,'mutual','彼此的','They soon discovered a mutual interest in music.');
INSERT INTO "toefl" VALUES(261,'roll','運作','They had to repeat the scene because the cameras weren''t rolling.');
INSERT INTO "toefl" VALUES(262,'overwhelming','勢不可擋的','She had the almost overwhelming desire to tell him the truth.');
INSERT INTO "toefl" VALUES(263,'monopoly','壟斷','Electricity, gas and water were considered to be natural monopolies.');
INSERT INTO "toefl" VALUES(264,'starfish','海星','NULL');
INSERT INTO "toefl" VALUES(265,'artifact','人工製品','NULL');
INSERT INTO "toefl" VALUES(266,'methane','甲烷','NULL');
INSERT INTO "toefl" VALUES(267,'horizon','地平線','A ship appeared on the horizon.');
INSERT INTO "toefl" VALUES(268,'turbulence','亂流','We experienced severe turbulence during the flight.');
INSERT INTO "toefl" VALUES(269,'engrave','雕','His name was engraved on the silver cup.');
INSERT INTO "toefl" VALUES(270,'molecule','分子','A molecule of water consists of two atoms of hydrogen and one atom of oxygen.');
INSERT INTO "toefl" VALUES(271,'plausible','合理的','The only plausible explanation is that he forgot.');
INSERT INTO "toefl" VALUES(272,'mild','輕微的','She looked at him in mild surprise.');
INSERT INTO "toefl" VALUES(273,'germinate','萌芽','An idea for a novel began to germinate in her mind.');
INSERT INTO "toefl" VALUES(274,'strait','窘境','She found herself in desperate financial straits.');
INSERT INTO "toefl" VALUES(275,'lamp','照射器','ultraviolet lamp');
INSERT INTO "toefl" VALUES(276,'cafeteria','自助餐廳','Consumer groups were urging school cafeterias to serve healthier food.');
INSERT INTO "toefl" VALUES(277,'cope','應付','Desert plants are adapted to cope with extreme heat.');
INSERT INTO "toefl" VALUES(278,'collaborate','合作','Researchers around the world are collaborating to develop a new vaccine.');
INSERT INTO "toefl" VALUES(279,'photosynthesis','光合作用','NULL');
INSERT INTO "toefl" VALUES(280,'confer','協商','He wanted to confer with his colleagues before reaching a decision.');
INSERT INTO "toefl" VALUES(281,'surplus','過剩','Wheat was in surplus that year.');
INSERT INTO "toefl" VALUES(282,'correlate','有關聯','A high-fat diet correlates with a greater risk of heart disease.');
INSERT INTO "toefl" VALUES(283,'parasite','寄生生物','He regards students as parasites on society');
INSERT INTO "toefl" VALUES(284,'peasant','農夫','NULL');
INSERT INTO "toefl" VALUES(285,'terrestrial','陸生的','terrestrial plants');
INSERT INTO "toefl" VALUES(286,'lyric','抒情的','NULL');
INSERT INTO "toefl" VALUES(287,'expedition','探險隊','Three members of the Everest expedition were killed.');
INSERT INTO "toefl" VALUES(288,'botany','植物學','NULL');
INSERT INTO "toefl" VALUES(289,'bulb','球莖','NULL');
INSERT INTO "toefl" VALUES(290,'burrow','找尋','She burrowed in the drawer for a pair of socks.');
INSERT INTO "toefl" VALUES(291,'thorough','徹底的','The police carried out a thorough investigation.');
INSERT INTO "toefl" VALUES(292,'longevity','長壽','We wish you both health and longevity.');
INSERT INTO "toefl" VALUES(293,'fauna','動物群','land and marine faunas');
INSERT INTO "toefl" VALUES(294,'mound','山丘','The castle was built on top of a natural grassy mound.');
INSERT INTO "toefl" VALUES(295,'lichen','地衣','NULL');
INSERT INTO "toefl" VALUES(296,'conquest','征服','conquest of poverty ');
INSERT INTO "toefl" VALUES(297,'condense','凝結','Steam condenses into water when it cools.');
INSERT INTO "toefl" VALUES(298,'metabolism','新陳代謝','The body''s metabolism is slowed down by extreme cold.');
INSERT INTO "toefl" VALUES(299,'exposition','解釋','NULL');
INSERT INTO "toefl" VALUES(300,'celestial','天空的','celestial bodies');
INSERT INTO "toefl" VALUES(301,'uranium','鈾','NULL');
INSERT INTO "toefl" VALUES(302,'scarce','稀少的','Details of the accident are scarce.');
INSERT INTO "toefl" VALUES(303,'mutate','突變',' the ability of the virus to mutate into new forms');
INSERT INTO "toefl" VALUES(304,'syllable','音節','‘Potato’ is stressed on the second syllable.');
INSERT INTO "toefl" VALUES(305,'photocopy','影印','I seem to have spent most of the day photocopying.');
INSERT INTO "toefl" VALUES(306,'fringe','邊緣','Nina remained on the fringe of the crowd.');
INSERT INTO "toefl" VALUES(307,'salvage','挽救','We only managed to salvage two paintings from the fire.');
INSERT INTO "toefl" VALUES(308,'consolidate','鞏固','With this new movie he has consolidated his position as the country''s leading director.');
INSERT INTO "toefl" VALUES(309,'criterion','標準','What criteria are used for assessing a student''s ability?');
INSERT INTO "toefl" VALUES(310,'pulse','脈動','A vein pulsed in his temple.');
INSERT INTO "toefl" VALUES(311,'orchestra','管絃樂隊','She plays the flute in the school orchestra.');
INSERT INTO "toefl" VALUES(312,'dwell','住在','He dwelt in a ruined cottage on the hillside.');
INSERT INTO "toefl" VALUES(313,'dean','院長','NULL');
INSERT INTO "toefl" VALUES(314,'inscribe','雕','His name was inscribed on the trophy.');
INSERT INTO "toefl" VALUES(315,'deed','行為','a tale of heroic deeds');
INSERT INTO "toefl" VALUES(316,'zinc','鋅','NULL');
INSERT INTO "toefl" VALUES(317,'divine','神聖的','divine law/love/will');
INSERT INTO "toefl" VALUES(318,'shale','頁岩','NULL');
INSERT INTO "toefl" VALUES(319,'calcium','鈣','NULL');
INSERT INTO "toefl" VALUES(320,'catastrophe','災難','Early warnings of rising water levels prevented another major catastrophe.');
INSERT INTO "toefl" VALUES(321,'stationary ','不動的','I remained stationary.');
INSERT INTO "toefl" VALUES(322,'thesis','論文','Students must submit a thesis on an agreed subject within four years.');
INSERT INTO "toefl" VALUES(323,'fission','分裂','Nuclear energy comes in two different flavors: fission  and fusion. ');
INSERT INTO "toefl" VALUES(324,'mantle','層','hills with a mantle of snow');
INSERT INTO "toefl" VALUES(325,'opaque','不清楚','The jargon in his talk was opaque to me.');
INSERT INTO "toefl" VALUES(326,'fragile ','易碎裂的','it''s very fragile.');
INSERT INTO "toefl" VALUES(327,'artisan','工匠','The hand-woven textiles were made by skilled local artisans.');
INSERT INTO "toefl" VALUES(328,'amino','氨','NULL');
INSERT INTO "toefl" VALUES(329,'blend','混和','Blend the flour with the milk to make a smooth paste.');
INSERT INTO "toefl" VALUES(330,'optic','視覺的','the optic nerve ');
INSERT INTO "toefl" VALUES(331,'illuminate','照射','The earth is illuminated by the sun.');
INSERT INTO "toefl" VALUES(332,'commit','犯罪','Most crimes are committed by young men.');
INSERT INTO "toefl" VALUES(333,'ingenious','巧妙的','His plots are always very ingenious.');
INSERT INTO "toefl" VALUES(334,'fort','堡壘','NULL');
INSERT INTO "toefl" VALUES(335,'imperial','帝國的','imperial power');
INSERT INTO "toefl" VALUES(336,'skeptic','懷疑者','I am a born skeptic.');
INSERT INTO "toefl" VALUES(337,'extrinsic','外在的','She was motivated by the idea of extrinsic rewards such as salary rather than intrinsic ones such as pride and self-respect.');
INSERT INTO "toefl" VALUES(338,'principal','重要的','The principal reason for this omission is lack of time.');
INSERT INTO "toefl" VALUES(339,'curtain','窗簾','It was ten in the morning but the curtains were still drawn.');
INSERT INTO "toefl" VALUES(340,'junction','交接處','It was near the junction of City Road and Old Street.');
INSERT INTO "toefl" VALUES(341,'incorporate','包含','The new car design incorporates all the latest safety features.');
INSERT INTO "toefl" VALUES(342,'radical','徹底的','the need for radical changes in education');
INSERT INTO "toefl" VALUES(343,'entrepreneur','企業家','NULL');
INSERT INTO "toefl" VALUES(344,'alphabet','字母','Alpha is the first letter of the Greek alphabet.');
INSERT INTO "toefl" VALUES(345,'cement','水泥','Use a mixture of one part cement to four parts sand.');
INSERT INTO "toefl" VALUES(346,'microbe','微生物','NULL');
INSERT INTO "toefl" VALUES(347,'presume','推測','I presumed him to be her husband.');
INSERT INTO "toefl" VALUES(348,'swift','立即的','The White House was swift to deny the rumours.');
INSERT INTO "toefl" VALUES(349,'constitute','構成','Does such an activity constitute a criminal offence?');
INSERT INTO "toefl" VALUES(350,'analogous','可比擬的','Sleep has often been thought of as being in some way analogous to death.');
INSERT INTO "toefl" VALUES(351,'impose','強加','This system imposes additional financial burdens on many people.');
INSERT INTO "toefl" VALUES(352,'fidelity','精確度','the fidelity of the translation to the original text');
INSERT INTO "toefl" VALUES(353,'facilitate','促進','Structured teaching facilitates learning.');
INSERT INTO "toefl" VALUES(354,'intervening','發生在其間的','Little had changed in the intervening years.');
INSERT INTO "toefl" VALUES(355,'tuition','指導','I studied dance for two years under her expert tuition.');
INSERT INTO "toefl" VALUES(356,'hemisphere','半球','NULL');
INSERT INTO "toefl" VALUES(357,'starve','飢餓','The new job doesn''t pay as much but we won't starve!');
INSERT INTO "toefl" VALUES(358,'archipelago','群島','NULL');
INSERT INTO "toefl" VALUES(359,'debris','殘骸','Several people were injured by flying debris in the explosion.');
INSERT INTO "toefl" VALUES(360,'reservoir','蓄水庫','NULL');
INSERT INTO "toefl" VALUES(361,'renovate','翻修','There will be extensive renovations to the hospital.');
INSERT INTO "toefl" VALUES(362,'calorie','卡路里','A fried egg contains about 100 calories.');
INSERT INTO "toefl" VALUES(363,'rigid','固執的','His rigid adherence to the rules made him unpopular.');
INSERT INTO "toefl" VALUES(364,'ore','礦砂','iron ore');
INSERT INTO "toefl" VALUES(365,'obscure','不清楚的','He was born around 1650 but his origins remain obscure.');
INSERT INTO "toefl" VALUES(366,'prestige','貴氣的','prestige items such as jewellery and silver');
INSERT INTO "toefl" VALUES(367,'limb','四肢','For a while, she lost the use of her limbs.');
INSERT INTO "toefl" VALUES(368,'iridium','銥','NULL');
INSERT INTO "toefl" VALUES(369,'acoustic','聽覺的','dogs have a much greater acoustic range than humans');
INSERT INTO "toefl" VALUES(370,'gulf','海灣','NULL');
INSERT INTO "toefl" VALUES(371,'ultraviolet','紫外線','ultraviolet rays ');
INSERT INTO "toefl" VALUES(372,'catalog','商品目錄','NULL');
INSERT INTO "toefl" VALUES(373,'gypsum','生石膏','NULL');
INSERT INTO "toefl" VALUES(374,'lethal','致命的','The snake''s venom is rarely lethal to humans.');
INSERT INTO "toefl" VALUES(375,'lift','取消','Martial law has now been lifted.');
INSERT INTO "toefl" VALUES(376,'legitimate','正當的','It seemed a perfectly legitimate question.');
INSERT INTO "toefl" VALUES(377,'endow','捐獻','In her will, she endowed a scholarship in the physics department.');
INSERT INTO "toefl" VALUES(378,'fledgling','雛鳥','NULL');
INSERT INTO "toefl" VALUES(379,'diameter','直徑','The dome is 42.3 metres in diameter.');
INSERT INTO "toefl" VALUES(380,'nomad','遊牧民族','NULL');
INSERT INTO "toefl" VALUES(381,'sergeant','警官','NULL');
INSERT INTO "toefl" VALUES(382,'withstand','禁得起','The materials used have to be able to withstand high temperatures.');
INSERT INTO "toefl" VALUES(383,'blanket','全面的','a blanket ban on tobacco advertising');
INSERT INTO "toefl" VALUES(384,'gully','溝渠','NULL');
INSERT INTO "toefl" VALUES(385,'realm','領域','At the end of the speech he seemed to be moving into the realms of fantasy.');
INSERT INTO "toefl" VALUES(386,'Eurasia','歐亞大陸','NULL');
INSERT INTO "toefl" VALUES(387,'mold','模子','A clay mold is used for casting bronze statues.');
INSERT INTO "toefl" VALUES(388,'aerosol','噴霧劑','aerosol spray');
INSERT INTO "toefl" VALUES(389,'watt','瓦特','NULL');
INSERT INTO "toefl" VALUES(390,'eel','鰻魚','NULL');
INSERT INTO "toefl" VALUES(391,'camouflage','偽裝的','Her angry words were camouflage for the way she felt.');
INSERT INTO "toefl" VALUES(392,'pitch','音程','A basic sense of rhythm and pitch is essential in a music teacher.');
INSERT INTO "toefl" VALUES(393,'offset','轉移抵銷','What expenses can you offset against tax?');
INSERT INTO "toefl" VALUES(394,'Peru','祕魯','NULL');
INSERT INTO "toefl" VALUES(395,'downtown','鬧區','NULL');
INSERT INTO "toefl" VALUES(396,'intrude','闖入','I''m sorry to intrude, but I need to talk to someone.');
INSERT INTO "toefl" VALUES(397,'tract','土地','They bought a 40-acre tract of land for development.');
INSERT INTO "toefl" VALUES(398,'fence','柵欄','NULL');
INSERT INTO "toefl" VALUES(399,'prevail','盛行','Those beliefs still prevail among certain social groups.');
INSERT INTO "toefl" VALUES(400,'propel','推進','He succeeded in propelling the ball across the line.');
INSERT INTO "toefl" VALUES(401,'mule','騾子','NULL');
INSERT INTO "toefl" VALUES(402,'stellar','星的','stellar light');
INSERT INTO "toefl" VALUES(403,'bud','萌芽','The tree is in bud already.');
INSERT INTO "toefl" VALUES(404,'rank','叢生的','an area overgrown with rank grass and nettles');
INSERT INTO "toefl" VALUES(405,'merchandise','商品','good business depends on having good merchandise');
INSERT INTO "toefl" VALUES(406,'anemone','海葵','NULL');
INSERT INTO "toefl" VALUES(407,'replenish','再填滿','Allow me to replenish your glass.');
INSERT INTO "toefl" VALUES(408,'accommodate','可容納','The aircraft is capable of accommodating 28 passengers.');
INSERT INTO "toefl" VALUES(409,'sheer','這','The area is under threat from the sheer number of tourists using it.');
INSERT INTO "toefl" VALUES(410,'onion','洋蔥','NULL');
INSERT INTO "toefl" VALUES(411,'syllabus','教學大綱','NULL');
INSERT INTO "toefl" VALUES(412,'deviate','越軌','He never deviated from his original plan.');
INSERT INTO "toefl" VALUES(413,'notion','想法',' I have to reject the notion that greed can be a good thing.');
INSERT INTO "toefl" VALUES(414,'embed','嵌進','an operation to remove glass that was embedded in his leg');
INSERT INTO "toefl" VALUES(415,'evoke','喚起','The music evoked memories of her youth.');
INSERT INTO "toefl" VALUES(416,'tame','馴化的','The bird became so tame that it was impossible to release it back into the wild.');
INSERT INTO "toefl" VALUES(417,'thaw','融化','The country was slowly thawing out after the long cold winter.');
INSERT INTO "toefl" VALUES(418,'zenith','天頂','The sun rose towards its zenith.');
INSERT INTO "toefl" VALUES(419,'empathy','察言觀色','The empathy between the two women was obvious.');
INSERT INTO "toefl" VALUES(420,'specimen','樣本','Redwood trees can live for a long time; one specimen is 4000 years old.');
INSERT INTO "toefl" VALUES(421,'membrane','薄膜','a waterproof membrane');
INSERT INTO "toefl" VALUES(422,'overcast','陰天','Today it will be dull and overcast.');
INSERT INTO "toefl" VALUES(423,'terrace','露臺','All rooms have a balcony or terrace.');
INSERT INTO "toefl" VALUES(424,'proliferate','激增','Books and articles on the subject have proliferated over the last year.');
INSERT INTO "toefl" VALUES(425,'sibling','手足','sibling rivalry');
INSERT INTO "toefl" VALUES(426,'pinpoint','精確的','The pilots bombed strategic targets with pinpoint accuracy.');
INSERT INTO "toefl" VALUES(427,'aquatic','水棲的','aquatic plants/life/ecosystems');
INSERT INTO "toefl" VALUES(428,'tertiary','第三的','NULL');
INSERT INTO "toefl" VALUES(429,'recur','發生多次','This theme recurs several times throughout the book.');
INSERT INTO "toefl" VALUES(430,'citrus','柑橘類','citrus fruit');
INSERT INTO "toefl" VALUES(431,'ornament','裝飾','The clock is simply for ornament; it doesn''t work any more.');
INSERT INTO "toefl" VALUES(432,'granite','花崗岩','NULL');
INSERT INTO "toefl" VALUES(433,'cactus','仙人掌','NULL');
INSERT INTO "toefl" VALUES(434,'sewer','下水道','NULL');
INSERT INTO "toefl" VALUES(435,'raft','木筏','an inflatable raft');
INSERT INTO "toefl" VALUES(436,'monsoon','印度的季風','NULL');
INSERT INTO "toefl" VALUES(437,'propagate','繁殖','The plant can be propagated from seed.');
INSERT INTO "toefl" VALUES(438,'deprive','剝奪','They were imprisoned and deprived of their basic rights.');
INSERT INTO "toefl" VALUES(439,'lunar','月亮的','a lunar eclipse');
INSERT INTO "toefl" VALUES(440,'advocate','提倡','The group does not advocate the use of violence.');
INSERT INTO "toefl" VALUES(441,'charcoal','木炭','NULL');
INSERT INTO "toefl" VALUES(442,'smear','弄髒','The children had smeared mud on the walls.');
INSERT INTO "toefl" VALUES(443,'retail','零售的','The recommended retail price is £9.99.');
INSERT INTO "toefl" VALUES(444,'vibrant','充滿活力的','Thailand is at its most vibrant during the New Year celebrations.');
INSERT INTO "toefl" VALUES(445,'lettuce','萵苣','Buy a lettuce and some tomatoes.');
INSERT INTO "toefl" VALUES(446,'holocene','全新紀','NULL');
INSERT INTO "toefl" VALUES(447,'amateur','業餘的','The tournament is open to both amateurs and professionals.');
INSERT INTO "toefl" VALUES(448,'desiccate','脫水','treeless and desiccated soil');
INSERT INTO "toefl" VALUES(449,'advent','到來','the advent of new technology');
INSERT INTO "toefl" VALUES(450,'cortex','器官皮層','NULL');
INSERT INTO "toefl" VALUES(451,'alpine','歐洲高山','A wide variety of alpine flowers can be found at all altitudes.');
INSERT INTO "toefl" VALUES(452,'flaw','缺陷','The argument is full of fundamental flaws.');
INSERT INTO "toefl" VALUES(453,'utensil','用具','cooking/kitchen utensils.');
INSERT INTO "toefl" VALUES(454,'diminish','變小','The world''s resources are rapidly diminishing.');
INSERT INTO "toefl" VALUES(455,'permeable','滲透性','The skin of amphibians is permeable to water.');
INSERT INTO "toefl" VALUES(456,'crevice','裂縫','Most of the year the insects are hidden in rock crevices.');
INSERT INTO "toefl" VALUES(457,'harness','馬具','NULL');
INSERT INTO "toefl" VALUES(458,'billboard','廣告牌','NULL');
INSERT INTO "toefl" VALUES(459,'cite','引用','She cited a passage from the President''s speech.');
INSERT INTO "toefl" VALUES(460,'friction','摩擦','Friction between moving parts had caused the engine to overheat.');
INSERT INTO "toefl" VALUES(461,'spectator','觀眾','NULL');
INSERT INTO "toefl" VALUES(462,'resonance','共鳴','Her voice had a strange and thrilling resonance.');
INSERT INTO "toefl" VALUES(463,'authentic','非假冒的','I don''t know if the painting is authentic.');
INSERT INTO "toefl" VALUES(464,'scribe','抄寫員','NULL');
INSERT INTO "toefl" VALUES(465,'landmass','大陸','NULL');
INSERT INTO "toefl" VALUES(466,'bulletin','公告','a bulletin on the President''s health');
INSERT INTO "toefl" VALUES(467,'egocentric','利己主義的','Young children are usually egocentric because they haven''t learnt other forms of behaviour.');
INSERT INTO "toefl" VALUES(468,'scent','氣味','The air was filled with the scent of wild flowers.');
INSERT INTO "toefl" VALUES(469,'Indonesia','印尼','NULL');
INSERT INTO "toefl" VALUES(470,'subtle','精湛的','I decided to try a more subtle approach.');
INSERT INTO "toefl" VALUES(471,'render','使得','Hundreds of people were rendered homeless by the earthquake.');
INSERT INTO "toefl" VALUES(472,'subside','平靜下來','When the rain had subsided we continued our walk.');
INSERT INTO "toefl" VALUES(473,'vague','模糊不清的','She''s a little vague about her plans for next year.');
INSERT INTO "toefl" VALUES(474,'grizzly','北美灰熊','NULL');
INSERT INTO "toefl" VALUES(475,'oxide','氧化物','iron oxide');
INSERT INTO "toefl" VALUES(476,'saline','含鹽的','Wash the lenses in saline solution.');
INSERT INTO "toefl" VALUES(477,'autonomous','自治的','Teachers aim to help children become autonomous learners.');
INSERT INTO "toefl" VALUES(478,'shrine','神殿',' a shrine to the Virgin Mary');
INSERT INTO "toefl" VALUES(479,'grape','葡萄','NULL');
INSERT INTO "toefl" VALUES(480,'finite','有限的','The world''s resources are finite.');
INSERT INTO "toefl" VALUES(481,'ironic','諷刺的','It''s ironic that she became a teacher—she used to hate school.');
INSERT INTO "toefl" VALUES(482,'slab','厚板','The road was paved with smooth stone slabs.');
INSERT INTO "toefl" VALUES(483,'spectacular','驚人的','It was a spectacular achievement on their part.');
INSERT INTO "toefl" VALUES(484,'peat','泥炭','peat extraction');
INSERT INTO "toefl" VALUES(485,'abrade','侵蝕','NULL');
INSERT INTO "toefl" VALUES(486,'Scandinavian','北歐的','NULL');
INSERT INTO "toefl" VALUES(487,'incentive','誘因','There is no incentive for people to save fuel.');
INSERT INTO "toefl" VALUES(488,'hive','蜂巢','NULL');
INSERT INTO "toefl" VALUES(489,'genus','屬','NULL');
INSERT INTO "toefl" VALUES(490,'Lincoln','林肯','NULL');
INSERT INTO "toefl" VALUES(491,'shed','棚',' a garden shed');
INSERT INTO "toefl" VALUES(492,'meteorology','氣象學','NULL');
INSERT INTO "toefl" VALUES(493,'dismiss','不考慮','He dismissed the opinion polls as worthless.');
INSERT INTO "toefl" VALUES(494,'spawn','產卵','NULL');
INSERT INTO "toefl" VALUES(495,'secrete','分泌','Insulin is secreted by the pancreas.');
INSERT INTO "toefl" VALUES(496,'immense','巨大的','There is still an immense amount of work to be done.');
INSERT INTO "toefl" VALUES(497,'pupa','蛹','NULL');
INSERT INTO "toefl" VALUES(498,'overlie','壓在上面','NULL');
INSERT INTO "toefl" VALUES(499,'roam','漫遊','The sheep are allowed to roam freely on this land.');
INSERT INTO "toefl" VALUES(500,'carnivore','肉食動物','NULL');
INSERT INTO "toefl" VALUES(501,'patron','贊助者','Frederick the Great was the patron of many artists.');
INSERT INTO "toefl" VALUES(502,'well-being','福利','We try to ensure the well-being of our employees.');
INSERT INTO "toefl" VALUES(503,'marsh','濕地','After so much rain, the field had become a marsh.');
INSERT INTO "toefl" VALUES(504,'prevalence','盛行','The disease is even more prevalent in Latin America.');
INSERT INTO "toefl" VALUES(505,'bulk','大部分','The bulk of the population lives in cities.');
INSERT INTO "toefl" VALUES(506,'mollusk','軟體動物','NULL');
INSERT INTO "toefl" VALUES(507,'calcite','方解石','NULL');
INSERT INTO "toefl" VALUES(508,'lump','塊狀物','This sauce has lumps in it.');
INSERT INTO "toefl" VALUES(509,'plaster','熟石膏','She broke her leg a month ago and it''s still in plaster.');
INSERT INTO "toefl" VALUES(510,'fluid','流質','The doctor told him to drink plenty of fluids.');
INSERT INTO "toefl" VALUES(511,'utilitarian','注重功能的','NULL');
INSERT INTO "toefl" VALUES(512,'anticipate','預期','We don''t anticipate any major problems.');
INSERT INTO "toefl" VALUES(513,'wagon','馬車','NULL');
INSERT INTO "toefl" VALUES(514,'profile','曝光度','We want to improve the profile of women''s health issues.');
INSERT INTO "toefl" VALUES(515,'Renaissance','文藝復興','NULL');
INSERT INTO "toefl" VALUES(516,'rid','清除','Further measures will be taken to rid our streets of crime.');
INSERT INTO "toefl" VALUES(517,'buffalo','水牛','NULL');
INSERT INTO "toefl" VALUES(518,'exterminate','根除','Fur seals were nearly exterminated a few years ago.');
INSERT INTO "toefl" VALUES(519,'tangible','可看見的','We cannot accept his findings without tangible evidence.');
INSERT INTO "toefl" VALUES(520,'dialogue','對話','The novel has long descriptions and not much dialogue.');
INSERT INTO "toefl" VALUES(521,'deteriorate','惡化','Her health deteriorated rapidly, and she died shortly afterwards.');
INSERT INTO "toefl" VALUES(522,'undercut','對..削價競爭','We were able to undercut our European rivals by 5%.');
INSERT INTO "toefl" VALUES(523,'wasp','黃蜂','NULL');
INSERT INTO "toefl" VALUES(524,'debt','欠款','I need to pay off all my debts before I leave the country.');
INSERT INTO "toefl" VALUES(525,'subsidy','津貼','agricultural subsidies');
INSERT INTO "toefl" VALUES(526,'steppe','大草原','NULL');
INSERT INTO "toefl" VALUES(527,'disseminate','散播','Their findings have been widely disseminated.');
INSERT INTO "toefl" VALUES(528,'Himalayas','喜馬拉雅山脈','NULL');
INSERT INTO "toefl" VALUES(529,'subliminal','下意識的','music containing subliminal messages');
INSERT INTO "toefl" VALUES(530,'prime','主要的','My prime concern is to protect my property.');
INSERT INTO "toefl" VALUES(531,'calligraphy','書法','NULL');
INSERT INTO "toefl" VALUES(532,'secular','非宗教的','Ours is a secular society.');
INSERT INTO "toefl" VALUES(533,'perpetual','連續不間斷的','How can I work with these perpetual interruptions?');
INSERT INTO "toefl" VALUES(534,'falcon','獵鷹','NULL');
INSERT INTO "toefl" VALUES(535,'leisure','空閒的','Make the most of your leisure time!');
INSERT INTO "toefl" VALUES(536,'prerequisite','不可或缺的','Flexibility of approach is an important prerequisite to successful learning.');
INSERT INTO "toefl" VALUES(537,'commute','通勤','She commutes from Oxford to London every day.');
INSERT INTO "toefl" VALUES(538,'disintegrate','解體','The plane disintegrated as it fell into the sea.');
INSERT INTO "toefl" VALUES(539,'haul','拉','The wagons were hauled by horses.');
INSERT INTO "toefl" VALUES(540,'distort','扭曲','The loudspeaker seemed to distort his voice');
INSERT INTO "toefl" VALUES(541,'chronology','年表','Historians seem to have confused the chronology of these events.');
INSERT INTO "toefl" VALUES(542,'diplomat','外交官','NULL');
INSERT INTO "toefl" VALUES(543,'Argentina','阿根廷','NULL');
INSERT INTO "toefl" VALUES(544,'deciduous','落葉性','NULL');
INSERT INTO "toefl" VALUES(545,'velocity','速率','NULL');
INSERT INTO "toefl" VALUES(546,'dung','糞肥','NULL');
INSERT INTO "toefl" VALUES(547,'staple','主要的','The staple crop is rice.');
INSERT INTO "toefl" VALUES(548,'sturdy','結實的','The vehicle is sturdy enough to withstand rough terrain.');
INSERT INTO "toefl" VALUES(549,'innate','天生的','He never lost his innate sense of fun.');
INSERT INTO "toefl" VALUES(550,'moral','道德的','Governments have at least a moral obligation to answer these questions.');
INSERT INTO "toefl" VALUES(551,'contend-with ','對付','Nurses often have to contend with violent or drunken patients.');
INSERT INTO "toefl" VALUES(552,'eukaryote','真核生物','NULL');
INSERT INTO "toefl" VALUES(553,'conceal','隱瞞','Tim could barely conceal his disappointment.');
INSERT INTO "toefl" VALUES(554,'eccentric','怪人','Most people considered him a harmless eccentric.');
INSERT INTO "toefl" VALUES(555,'agitate','攪拌','Agitate the mixture to dissolve the powder.');
INSERT INTO "toefl" VALUES(556,'seam','礦層','They struck a rich seam of iron ore.');
INSERT INTO "toefl" VALUES(557,'Hungarian','匈牙利人','NULL');
INSERT INTO "toefl" VALUES(558,'mediate','影響成真','Educational success is mediated by economic factors.');
INSERT INTO "toefl" VALUES(559,'darkroom','照片沖洗室','NULL');
INSERT INTO "toefl" VALUES(560,'mammoth','長毛象','NULL');
INSERT INTO "toefl" VALUES(561,'boulder','大圓石','NULL');
INSERT INTO "toefl" VALUES(562,'commodity','商品','Crude oil is the world''s most important commodity.');
INSERT INTO "toefl" VALUES(563,'protrude','突出',' He hung his coat on a nail protruding from the wall.');
INSERT INTO "toefl" VALUES(564,'jewelry','珠寶','NULL');
INSERT INTO "toefl" VALUES(565,'bead','水滴','There were beads of sweat on his forehead.');
INSERT INTO "toefl" VALUES(566,'worthwhile','值得的','The smile on her face made it all worthwhile.');
INSERT INTO "toefl" VALUES(567,'spite','惡意','I''m sure he only said it out of spite.');
INSERT INTO "toefl" VALUES(568,'rodent','齧齒動物','NULL');
INSERT INTO "toefl" VALUES(569,'counsel','聆聽','Therapists were brought in to counsel the bereaved.');
INSERT INTO "toefl" VALUES(570,'nucleus','核','NULL');
INSERT INTO "toefl" VALUES(571,'Pakistan','巴基斯坦','NULL');
INSERT INTO "toefl" VALUES(572,'detach','分離','Detach the coupon and return it as soon as possible');
INSERT INTO "toefl" VALUES(573,'intact','完好如初','Most of the house remains intact even after two hundred years.');
INSERT INTO "toefl" VALUES(574,'assimilate','吸收','The committee will need time to assimilate this report.');
INSERT INTO "toefl" VALUES(575,'exert','運用','He exerted all his authority to make them accept the plan.');
INSERT INTO "toefl" VALUES(576,'amphibian','兩棲類動物','NULL');
INSERT INTO "toefl" VALUES(577,'induce','引誘','Nothing would induce me to take the job.');
INSERT INTO "toefl" VALUES(578,'residual','剩餘的','There are still a few residual problems with the computer program.');
INSERT INTO "toefl" VALUES(579,'dormant','冬眠的','During the winter the seeds lie dormant in the soil.');
INSERT INTO "toefl" VALUES(580,'famine','飢荒','disasters such as floods and famine');
INSERT INTO "toefl" VALUES(581,'spontaneous','不自主的','The audience burst into spontaneous applause.');
INSERT INTO "toefl" VALUES(582,'rehearse','排練','We were given only two weeks to rehearse.');
INSERT INTO "toefl" VALUES(583,'buoyancy','浮力','Salt water is more buoyant than fresh water.');
INSERT INTO "toefl" VALUES(584,'hydrology','水文學','NULL');
INSERT INTO "toefl" VALUES(585,'restrain','克制','I restrained the urge to punch him.');
INSERT INTO "toefl" VALUES(586,'remnant','遺跡','The woods are remnants of a huge forest which once covered the whole area.');
INSERT INTO "toefl" VALUES(587,'revolve-around','沿軌道轉','The earth revolves around the sun.');
INSERT INTO "toefl" VALUES(588,'peril','危險','The country''s economy is now in grave peril.');
INSERT INTO "toefl" VALUES(589,'elicit','引誘','I could elicit no response from him.');
INSERT INTO "toefl" VALUES(590,'dilute','稀釋','The paint can be diluted with water to make a lighter shade.');
INSERT INTO "toefl" VALUES(591,'meadow','草地','NULL');
INSERT INTO "toefl" VALUES(592,'deity','神','NULL');
INSERT INTO "toefl" VALUES(593,'soluble','可溶的','Glucose is soluble in water.');
INSERT INTO "toefl" VALUES(594,'generosity','大方','He treated them with generosity and thoughtfulness.');
INSERT INTO "toefl" VALUES(595,'adept','擅長的','He became adept at getting even the shyest students to talk.');
INSERT INTO "toefl" VALUES(596,'strand','海濱','NULL');
INSERT INTO "toefl" VALUES(597,'via','藉由','We flew home via Dubai.');
INSERT INTO "toefl" VALUES(598,'monotony','單調','She watches television to relieve the monotony of everyday life.');
INSERT INTO "toefl" VALUES(599,'sparse','稀疏的','Vegetation becomes sparse higher up the mountains');
INSERT INTO "toefl" VALUES(600,'furnace','火爐','NULL');
INSERT INTO "toefl" VALUES(601,'incline','傾向','I incline to the view that we should take no action at this stage.');
INSERT INTO "toefl" VALUES(602,'urchin','海膽','NULL');
INSERT INTO "toefl" VALUES(603,'Persia','波斯','NULL');
INSERT INTO "toefl" VALUES(604,'tempt','誘惑','Don''t tempt thieves by leaving valuables clearly visible.');
INSERT INTO "toefl" VALUES(605,'jar','發出刺耳聲','The jolt seemed to jar every bone in her body.');
INSERT INTO "toefl" VALUES(606,'resin','樹酯','NULL');
INSERT INTO "toefl" VALUES(607,'replica','複製品','Amy was a younger replica of her mother.');
INSERT INTO "toefl" VALUES(608,'locomotive','火車頭','NULL');
INSERT INTO "toefl" VALUES(609,'credential','憑證','NULL');
INSERT INTO "toefl" VALUES(610,'inadvertently ','不小心地','We had inadvertently left without paying the bill.');
INSERT INTO "toefl" VALUES(611,'cone','毬果','NULL');
INSERT INTO "toefl" VALUES(612,'bounce','彈起','The ball bounced twice before he could reach it.');
INSERT INTO "toefl" VALUES(613,'subsist','維持生活','Old people often subsist on very small incomes.');
INSERT INTO "toefl" VALUES(614,'igloo','雪屋','NULL');
INSERT INTO "toefl" VALUES(615,'cargo','貨物','The tanker began to spill its cargo of oil.');
INSERT INTO "toefl" VALUES(616,'buck','羚羊','NULL');
INSERT INTO "toefl" VALUES(617,'laden','滿載的','The trees were laden with apples.');
INSERT INTO "toefl" VALUES(618,'foster','促進','The club''s aim is to foster better relations within the community.');
INSERT INTO "toefl" VALUES(619,'allude-to','暗示','The problem had been alluded to briefly in earlier discussions.');
INSERT INTO "toefl" VALUES(620,'undergraduate','大學生','NULL');
INSERT INTO "toefl" VALUES(621,'precarious','不安定的','He earned a precarious living as an artist.');
INSERT INTO "toefl" VALUES(622,'meticulous','小心翼翼的','She planned her trip in meticulous detail.');
INSERT INTO "toefl" VALUES(623,'chant','詠唱','The crowd broke into chants of ‘Out! Out!’');
INSERT INTO "toefl" VALUES(624,'metaphor','象徵','a game of football used as a metaphor for the competitive struggle of life');
INSERT INTO "toefl" VALUES(625,'brittle','易碎的','The paint was brittle with age.');
INSERT INTO "toefl" VALUES(626,'counterpart','互補的事物','The Foreign Minister held talks with his Chinese counterpart.');
INSERT INTO "toefl" VALUES(627,'tactic','手法','They tried all kinds of tactics to get us to go.');
INSERT INTO "toefl" VALUES(628,'rigorous','嚴謹的','The second team adopted a much more rigorous approach to the problem.');
INSERT INTO "toefl" VALUES(629,'swirl','打旋','The water swirled down the drain.');
INSERT INTO "toefl" VALUES(630,'demise','死亡','NULL');
INSERT INTO "toefl" VALUES(631,'primate','靈長類','NULL');
INSERT INTO "toefl" VALUES(632,'metropolitan','大都市','NULL');
INSERT INTO "toefl" VALUES(633,'oversee','監督','United Nations observers oversaw the elections.');
INSERT INTO "toefl" VALUES(634,'makeup ','性格','Jealousy is not part of his make-up.');
INSERT INTO "toefl" VALUES(635,'deceive','欺騙','Her husband had been deceiving her for years.');
INSERT INTO "toefl" VALUES(636,'plumbing','管線','The houses were thoroughly refitted with proper plumbing . ');
INSERT INTO "toefl" VALUES(637,'curriculum','課程','Spanish is in the curriculum.');
INSERT INTO "toefl" VALUES(638,'drapery','皺褶布','The style is noted for its flowing drapery.');
INSERT INTO "toefl" VALUES(639,'astronaut','太空人','NULL');
INSERT INTO "toefl" VALUES(640,'invoke','引用','She invoked several eminent scholars to back up her argument.');
INSERT INTO "toefl" VALUES(641,'impetus','衝勁','The debate seems to have lost much of its initial impetus.');
INSERT INTO "toefl" VALUES(642,'sodium','鈉','NULL');
INSERT INTO "toefl" VALUES(643,'recreation','娛樂','the need to improve facilities for leisure and recreation');
INSERT INTO "toefl" VALUES(644,'pertain','適用','Those laws no longer pertain.');
INSERT INTO "toefl" VALUES(645,'sulfate','硫酸鹽','NULL');
INSERT INTO "toefl" VALUES(646,'conspicuous','顯著的','Bay windows are a conspicuous feature of his architecture.');
INSERT INTO "toefl" VALUES(647,'basalt','玄武岩','NULL');
INSERT INTO "toefl" VALUES(648,'mundane','俗世','NULL');
INSERT INTO "toefl" VALUES(649,'comprise','組成','The collection comprises 327 paintings.');
INSERT INTO "toefl" VALUES(650,'sacred','神聖的','Cows are sacred to Hindus.');
INSERT INTO "toefl" VALUES(651,'scant','不足的','There is scant evidence for this view.');
INSERT INTO "toefl" VALUES(652,'prolong','延長','The operation could prolong his life by two or three years.');
INSERT INTO "toefl" VALUES(653,'tectonics','構造地質學','NULL');
INSERT INTO "toefl" VALUES(654,'anomaly','異常','the many anomalies in the tax system');
INSERT INTO "toefl" VALUES(655,'dike','防護欄','They built a temporary dike of sandbags to keep the river from flooding the town. ');
INSERT INTO "toefl" VALUES(656,'surpass','勝過','He hopes one day to surpass the world record.');
INSERT INTO "toefl" VALUES(657,'goose','鵝','NULL');
INSERT INTO "toefl" VALUES(658,'incur','招惹','She had incurred the wrath of her father by marrying without his consent');
INSERT INTO "toefl" VALUES(659,'fragrance','香味','The flowers are chosen for their delicate fragrance.');
INSERT INTO "toefl" VALUES(660,'convict','說服','There wasn''t enough evidence to convict her.');
INSERT INTO "toefl" VALUES(661,'cord','繩','NULL');
INSERT INTO "toefl" VALUES(662,'choke','噎到','He was choking on a piece of toast.');
INSERT INTO "toefl" VALUES(663,'adorn','裝扮','The children adorned themselves with flowers.');
INSERT INTO "toefl" VALUES(664,'streak','條紋','There was a streak of blood on his face.');
INSERT INTO "toefl" VALUES(665,'wool','毛製品','This scarf is 100% wool.');
INSERT INTO "toefl" VALUES(666,'dye','染','She dyed her hair blonde.');
INSERT INTO "toefl" VALUES(667,'devoid','缺乏的','The letter was devoid of warmth and feeling.');
INSERT INTO "toefl" VALUES(668,'interlock','固定在一起','The US space shuttle will interlock with the Russian space station later today.');
INSERT INTO "toefl" VALUES(669,'substratum','下層','NULL');
INSERT INTO "toefl" VALUES(670,'relic','遺物','Videotapes may already seem like relics of a bygone era.');
INSERT INTO "toefl" VALUES(671,'bizarre','奇異的','bizarre behaviour');
INSERT INTO "toefl" VALUES(672,'cellulose','纖維素','NULL');
INSERT INTO "toefl" VALUES(673,'barn','穀倉','a hay barn');
INSERT INTO "toefl" VALUES(674,'dismantle','拆','I had to dismantle the engine in order to repair it.');
INSERT INTO "toefl" VALUES(675,'feat','功績','The tunnel is a brilliant feat of engineering.');
INSERT INTO "toefl" VALUES(676,'disguise','隱藏','He tried to disguise his accent.');
INSERT INTO "toefl" VALUES(677,'rudimentary','初步的','They were given only rudimentary training in the job.');
INSERT INTO "toefl" VALUES(678,'cult','狂熱','An extraordinary personality cult had been created around the leader.');
INSERT INTO "toefl" VALUES(679,'cushion','墊狀物','Underlay forms a cushion between the carpet and the floor, to minimize wear.');
INSERT INTO "toefl" VALUES(680,'tangle','混亂的','His financial affairs are in a tangle.');
INSERT INTO "toefl" VALUES(681,'crawl','爬行','There''s a spider crawling up your leg.');
INSERT INTO "toefl" VALUES(682,'entail','需要','The job entails a lot of hard work.');
INSERT INTO "toefl" VALUES(683,'miniature','小型的','Some parents dress their children like miniature adults.');
INSERT INTO "toefl" VALUES(684,'indigenous','本地的','The kangaroo is indigenous to Australia.');
INSERT INTO "toefl" VALUES(685,'Chile','智利','NULL');
INSERT INTO "toefl" VALUES(686,'inordinate','無預期的','The strike has led to inordinate delays.');
INSERT INTO "toefl" VALUES(687,'bovine','牛科動物','NULL');
INSERT INTO "toefl" VALUES(688,'virtuosity','精湛技藝','a performance of breathtaking virtuosity');
INSERT INTO "toefl" VALUES(689,'quartet','四重奏','NULL');
INSERT INTO "toefl" VALUES(690,'percolate','滲透','Nitrates may take 20 years to percolate through to the underground streams.');
INSERT INTO "toefl" VALUES(691,'elapse','逝去','Many years elapsed before they met again.');
INSERT INTO "toefl" VALUES(692,'spare','備用的','Take some spare clothes in case you get wet.');
INSERT INTO "toefl" VALUES(693,'vacant','未被使用的','There is a room vacant, as it happens.');
INSERT INTO "toefl" VALUES(694,'genuine','名符其實的','Only genuine refugees can apply for asylum.');
INSERT INTO "toefl" VALUES(695,'gallop','奔馳','The terrified horse galloped off.');
INSERT INTO "toefl" VALUES(696,'solstice','冬至/夏至','NULL');
INSERT INTO "toefl" VALUES(697,'constituent','成分','Silicon and oxygen are the fundamental constituents of rocks in the earth''s crust.');
INSERT INTO "toefl" VALUES(698,'pant','呼吸急促','She finished the race panting heavily.');
INSERT INTO "toefl" VALUES(699,'Portugal','葡萄牙','NULL');
INSERT INTO "toefl" VALUES(700,'jurisdiction','裁判權','These matters do not fall within our jurisdiction.');
INSERT INTO "toefl" VALUES(701,'respiration','呼吸作用','Blood pressure and respiration are also recorded.');
INSERT INTO "toefl" VALUES(702,'potent','有力的','a potent drug');
INSERT INTO "toefl" VALUES(703,'emanate','散發','He emanates power and confidence.');
INSERT INTO "toefl" VALUES(704,'surmise','猜測','From the looks on their faces, I surmised that they had had an argument.');
INSERT INTO "toefl" VALUES(705,'expend','耗費','Most animals expend a lot of energy searching for food.');
INSERT INTO "toefl" VALUES(706,'mandatory','義務的','The offence carries a mandatory life sentence.');
INSERT INTO "toefl" VALUES(707,'abound-with','富含','The lakes abound with fish.');
INSERT INTO "toefl" VALUES(708,'perplex','困惑','They were perplexed by her response.');
INSERT INTO "toefl" VALUES(709,'cumbersome','笨重的','The organization changed its cumbersome title to something easier to remember.');
INSERT INTO "toefl" VALUES(710,'aerate','通風','Earthworms do the important job of aerating the soil.');
INSERT INTO "toefl" VALUES(711,'perish','死','Thousands perished at the hands of the invading forces.');
INSERT INTO "toefl" VALUES(712,'lily','百合花','NULL');
INSERT INTO "toefl" VALUES(713,'soar','激升','Unemployment has soared to 18%.');
INSERT INTO "toefl" VALUES(714,'instigate','煽動','They were accused of instigating racial violence.');
INSERT INTO "toefl" VALUES(715,'trample','踐踏','He was trampled to death by a runaway horse.');
INSERT INTO "toefl" VALUES(716,'unravel','釐清','The discovery will help scientists unravel the mystery of the Ice Age.');
INSERT INTO "toefl" VALUES(717,'audition','試聽','Hundreds of people auditioned.');
INSERT INTO "toefl" VALUES(718,'demographics','人口統計學','NULL');
INSERT INTO "toefl" VALUES(719,'self-image','自我定位','NULL');
INSERT INTO "toefl" VALUES(720,'ingest','攝取','Food is the major source of ingested bacteria.');
INSERT INTO "toefl" VALUES(721,'pacify','平息','The speech was designed to pacify the irate crowd.');
INSERT INTO "toefl" VALUES(722,'insult','侮辱','I have never been so insulted in my life!');
INSERT INTO "toefl" VALUES(723,'corroborate','證實','The evidence was corroborated by two independent witnesses.');
INSERT INTO "toefl" VALUES(724,'diesel','吃柴油的','Our new car is a diesel.');
INSERT INTO "toefl" VALUES(725,'anatomy','解剖學','NULL');
INSERT INTO "toefl" VALUES(726,'mangrove','紅樹林','NULL');
INSERT INTO "toefl" VALUES(727,'Christian','基督徒','NULL');
INSERT INTO "toefl" VALUES(728,'infirm','體弱的','to grow old and infirm');
INSERT INTO "toefl" VALUES(729,'orchid','蘭花','NULL');
INSERT INTO "toefl" VALUES(730,'alongside','在旁地','Nick caught up with me and rode alongside.');
INSERT INTO "toefl" VALUES(731,'tusk','象牙','NULL');
INSERT INTO "toefl" VALUES(732,'willow','柳','NULL');
INSERT INTO "toefl" VALUES(733,'mediocre','二流的','I thought the play was only mediocre.');
INSERT INTO "toefl" VALUES(734,'cart','推車','NULL');
INSERT INTO "toefl" VALUES(735,'hostile','敵意的','The speaker got a hostile reception from the audience.');
INSERT INTO "toefl" VALUES(736,'choreography','編舞','NULL');
INSERT INTO "toefl" VALUES(737,'fountain','噴泉','NULL');
INSERT INTO "toefl" VALUES(738,'verge-on','幾乎','Some of his suggestions verged on the outrageous.');
INSERT INTO "toefl" VALUES(739,'daisy','雛菊','NULL');
INSERT INTO "toefl" VALUES(740,'adhere','附著','There was oil adhering to the bird''s feathers.');
INSERT INTO "toefl" VALUES(741,'chimney','煙囪','NULL');
INSERT INTO "toefl" VALUES(742,'erratic','不穩定','The electricity supply here is quite erratic.');
INSERT INTO "toefl" VALUES(743,'manifest','展現了','Social tensions were manifested in the recent political crisis.');
INSERT INTO "toefl" VALUES(744,'elusive','難以解決的','A solution to the problem of toxic waste is proving elusive.');
INSERT INTO "toefl" VALUES(745,'prone','易於','Working without a break makes you more prone to error.');
INSERT INTO "toefl" VALUES(746,'theocracy','神權統治','NULL');
INSERT INTO "toefl" VALUES(747,'hinder','阻礙','Some teachers felt hindered by a lack of resources.');
INSERT INTO "toefl" VALUES(748,'cello','大提琴','NULL');
INSERT INTO "toefl" VALUES(749,'reciprocal','雙向的','The two colleges have a reciprocal arrangement whereby students from one college can attend classes at the other.');
INSERT INTO "toefl" VALUES(750,'aggregate','總計','The scores were aggregated with the first round totals to decide the winner.');
INSERT INTO "toefl" VALUES(751,'avenue','大道','NULL');
INSERT INTO "toefl" VALUES(752,'flora','植物群','rare species of flora and fauna');
INSERT INTO "toefl" VALUES(753,'endorse','背書','I wonder how many celebrities actually use the products they endorse.');
INSERT INTO "toefl" VALUES(754,'arduous','艱鉅的','The work was arduous.');
INSERT INTO "toefl" VALUES(755,'symmetric','對稱的','People''s bodies are never quite symmetrical.');
INSERT INTO "toefl" VALUES(756,'attest','證實','Contemporary accounts attest to his courage and determination.');
INSERT INTO "toefl" VALUES(757,'hydrocarbon','碳氫化合物','NULL');
INSERT INTO "toefl" VALUES(758,'dissipate','消散','Eventually, his anger dissipated.');
INSERT INTO "toefl" VALUES(759,'bold','勇敢的','The wine made him bold enough to approach her.');
INSERT INTO "toefl" VALUES(760,'commemorate','紀念','A plaque commemorates the battle.');
INSERT INTO "toefl" VALUES(761,'reign','統治','Queen Victoria reigned from 1837 to 1901.');
INSERT INTO "toefl" VALUES(762,'ooze','流出','Blood oozed out of the wound.');
INSERT INTO "toefl" VALUES(763,'mat','黯淡的','Prints are available on mat or glossy paper.');
INSERT INTO "toefl" VALUES(764,'immerse','沉浸','The seeds will swell when immersed in water.');
INSERT INTO "toefl" VALUES(765,'fierce','猛烈的','He launched a fierce attack on the Democrats.');
INSERT INTO "toefl" VALUES(766,'zigzag','Z字形','The path descended the hill in a series of zigzags.');
INSERT INTO "toefl" VALUES(767,'synonym','同義字','‘Big’ and ‘large’ are synonyms.');
INSERT INTO "toefl" VALUES(768,'threshold','轉捩點','She felt as though she was on the threshold of a new life.');
INSERT INTO "toefl" VALUES(769,'postpone','延後','We''ll have to postpone the meeting until next week.');
INSERT INTO "toefl" VALUES(770,'peach','桃子','NULL');
INSERT INTO "toefl" VALUES(771,'Jurassic','侏儸紀','NULL');
INSERT INTO "toefl" VALUES(772,'chloride','氯化物','NULL');
INSERT INTO "toefl" VALUES(773,'lithograph','平版印刷','NULL');
INSERT INTO "toefl" VALUES(774,'deem','視為','I deem it an honour to be invited.');
INSERT INTO "toefl" VALUES(775,'hybrid','混種','A mule is a hybrid of a male donkey and a female horse.');
INSERT INTO "toefl" VALUES(776,'rebound','彈回','Share prices rebounded after Friday''s losses.');
INSERT INTO "toefl" VALUES(777,'liberate','解放','The city was liberated by the advancing army.');
INSERT INTO "toefl" VALUES(778,'dictate','主宰','It''s generally your job that dictates where you live now.');
INSERT INTO "toefl" VALUES(779,'Roosevelt','羅斯福','NULL');
INSERT INTO "toefl" VALUES(780,'awkward','尷尬的','There was an awkward silence.');
INSERT INTO "toefl" VALUES(781,'rye','黑麥','NULL');
INSERT INTO "toefl" VALUES(782,'bombard','轟炸','Madrid was heavily bombarded for several months.');
INSERT INTO "toefl" VALUES(783,'intricate','複雜的','intricate patterns');
INSERT INTO "toefl" VALUES(784,'myriad','大量','Designs are available in a myriad of colours.');
INSERT INTO "toefl" VALUES(785,'unanimous','一致的','She was the unanimous choice of the selection committee.');
INSERT INTO "toefl" VALUES(786,'outwash','冰水沉積','NULL');
INSERT INTO "toefl" VALUES(787,'scribble','潦草的寫',' He scribbled a note to his sister before leaving.');
INSERT INTO "toefl" VALUES(788,'conducive','有助於','The soft lights and music were conducive to a relaxed atmosphere.');
INSERT INTO "toefl" VALUES(789,'barley','大麥','NULL');
INSERT INTO "toefl" VALUES(790,'pantomime','啞劇','He has also appeared in pantomime.');
INSERT INTO "toefl" VALUES(791,'beetle','甲蟲','NULL');
INSERT INTO "toefl" VALUES(792,'ion','離子','NULL');
INSERT INTO "toefl" VALUES(793,'chronic','慢性的','a chronic alcoholic/depressive');
INSERT INTO "toefl" VALUES(794,'pit','洞','We dug a deep pit in the yard.');
INSERT INTO "toefl" VALUES(795,'well-to-do','有錢的','They''re very well-to-do.');
INSERT INTO "toefl" VALUES(796,'walrus','海象','NULL');
INSERT INTO "toefl" VALUES(797,'liter','公升','NULL');
INSERT INTO "toefl" VALUES(798,'spike','尖刺','a row of iron spikes on a wall');
INSERT INTO "toefl" VALUES(799,'spout','噴','The wound was still spouting blood.');
INSERT INTO "toefl" VALUES(800,'patent','專利權','The device was protected by patent.');
INSERT INTO "toefl" VALUES(801,'Mongolia','蒙古','NULL');
INSERT INTO "toefl" VALUES(802,'improvise','就地取材','There isn''t much equipment. We're going to have to improvise.');
INSERT INTO "toefl" VALUES(803,'trivia','不重要的事','We spent the whole evening discussing domestic trivia.');
INSERT INTO "toefl" VALUES(804,'splendor','華麗','The palace has been restored to its former splendor.');
INSERT INTO "toefl" VALUES(805,'engulf','吞沒','He was engulfed by a crowd of reporters.');
INSERT INTO "toefl" VALUES(806,'encroach','覆蓋','The growing town soon encroached on the surrounding countryside.');
INSERT INTO "toefl" VALUES(807,'magnificent','棒','You''ve all done a magnificent job.');
INSERT INTO "toefl" VALUES(808,'boast','吹牛','I don''t want to boast, but I can actually speak six languages.');
INSERT INTO "toefl" VALUES(809,'sandbar','沙洲','NULL');
INSERT INTO "toefl" VALUES(810,'paramount','至高無上的','The welfare of the child must always be the court''s paramount consideration');
INSERT INTO "toefl" VALUES(811,'infrared','紅外線','NULL');
INSERT INTO "toefl" VALUES(812,'emulsion','乳膠漆','They gave the walls a coat of white emulsion.');
INSERT INTO "toefl" VALUES(813,'lavish','揮霍的','They lived a very lavish lifestyle.');
INSERT INTO "toefl" VALUES(814,'jut','突出','A row of small windows jutted out from the roof.');
INSERT INTO "toefl" VALUES(815,'crest','雞冠','The male is recognizable by its yellow crest.');
INSERT INTO "toefl" VALUES(816,'align','對齊','The top and bottom line of each column on the page should align.');
INSERT INTO "toefl" VALUES(817,'foreground','靠最近的','The figure in the foreground is the artist''s mother.');
INSERT INTO "toefl" VALUES(818,'discern','察覺','I quickly discerned that something was wrong.');
INSERT INTO "toefl" VALUES(819,'omit','排除','If you are a student, you can omit questions 16–18.');
INSERT INTO "toefl" VALUES(820,'posture','姿勢','Back pains can be the result of bad posture.');
INSERT INTO "toefl" VALUES(821,'hip','臀骨','These jeans are too tight around the hips.');
INSERT INTO "toefl" VALUES(822,'flier','飛行物','Butterflies can be strong flyers.');
INSERT INTO "toefl" VALUES(823,'engender','衍生','The issue engendered controversy.');
INSERT INTO "toefl" VALUES(824,'impede','延期','Work on the building was impeded by severe weather.');
INSERT INTO "toefl" VALUES(825,'dwindle','縮減','Membership of the club has dwindled from 70 to 20.');
INSERT INTO "toefl" VALUES(826,'superficial','表面的','The book shows only a superficial understanding of the historical context.');
INSERT INTO "toefl" VALUES(827,'heir','繼承人','the heir to the throne ');
INSERT INTO "toefl" VALUES(828,'augment','增強','This carbon dioxide will thicken the atmosphere and augment greenhouse warming.');
INSERT INTO "toefl" VALUES(829,'lumber','木材','NULL');
INSERT INTO "toefl" VALUES(830,'underpin ','支撐','The report is underpinned by extensive research.');
INSERT INTO "toefl" VALUES(831,'sentiment','情感','Public sentiment is against any change to the law.');
INSERT INTO "toefl" VALUES(832,'divert','使改道','The course of the stream has now been diverted.');
INSERT INTO "toefl" VALUES(833,'olfactory','嗅覺','NULL');
INSERT INTO "toefl" VALUES(834,'affluent','繁榮','a very affluent neighbourhood');
INSERT INTO "toefl" VALUES(835,'violet','紫色','NULL');
INSERT INTO "toefl" VALUES(836,'spoil','惡化','The tall buildings have spoiled the view.');
INSERT INTO "toefl" VALUES(837,'motif','圖案','wallpaper with a flower motif');
INSERT INTO "toefl" VALUES(838,'enact','頒布','legislation enacted by parliament');
INSERT INTO "toefl" VALUES(839,'egalitarian','平等的','an egalitarian society');
INSERT INTO "toefl" VALUES(840,'squeal','尖叫','Children were running around squealing with excitement.');
INSERT INTO "toefl" VALUES(841,'vicinity','附近','There is no hospital in the immediate vicinity.');
INSERT INTO "toefl" VALUES(842,'mason','石匠','NULL');
INSERT INTO "toefl" VALUES(843,'silicon','矽','NULL');
INSERT INTO "toefl" VALUES(844,'hub','重要的部分','The kitchen was the hub of family life.');
INSERT INTO "toefl" VALUES(845,'detriment','危害','Wood accounts for 90% of energy production in some countries, with consequent environmental detriment.');
INSERT INTO "toefl" VALUES(846,'foremost','首要的','This question has been foremost in our minds recently.');
INSERT INTO "toefl" VALUES(847,'stealth','伏擊','Lions rely on stealth when hunting.');
INSERT INTO "toefl" VALUES(848,'peripheral','周圍/不重要的','Fund-raising is peripheral to their main activities.');
INSERT INTO "toefl" VALUES(849,'influx','湧入','the influx of wealth into the region');
INSERT INTO "toefl" VALUES(850,'legume','豆科植物','NULL');
INSERT INTO "toefl" VALUES(851,'encapsulate','簡短的話講述重要事物','The poem encapsulates many of the central themes of her writing.');
INSERT INTO "toefl" VALUES(852,'ideology','意識形態','Marxist/capitalist ideology');
INSERT INTO "toefl" VALUES(853,'traverse','橫跨過','The region is traversed by several roads.');
INSERT INTO "toefl" VALUES(854,'asymmetric','非對稱','Most people''s faces are asymmetric.');
INSERT INTO "toefl" VALUES(855,'gist','要旨','Students are taught the skills of reading and listening for gist.');
INSERT INTO "toefl" VALUES(856,'Swiss','瑞士人','NULL');
INSERT INTO "toefl" VALUES(857,'diploma','文憑','a High School diploma');
INSERT INTO "toefl" VALUES(858,'regime','政權','NULL');
INSERT INTO "toefl" VALUES(859,'vacuum','真空','a vacuum pump ');
INSERT INTO "toefl" VALUES(860,'clam','蛤','NULL');
INSERT INTO "toefl" VALUES(861,'slender','微小的','Australia held a slender 1–0 lead at half-time.');
INSERT INTO "toefl" VALUES(862,'acre','英畝','NULL');
INSERT INTO "toefl" VALUES(863,'adamant','堅決','Eva was adamant that she would not come.');
INSERT INTO "toefl" VALUES(864,'pliable','易彎的','The plant has long pliable stems.');
INSERT INTO "toefl" VALUES(865,'paucity','缺乏','a paucity of information');
INSERT INTO "toefl" VALUES(866,'sew','縫','My mother taught me how to sew.');
INSERT INTO "toefl" VALUES(867,'nope','沒有','‘Have you seen my pen?’ ‘Nope.’');
INSERT INTO "toefl" VALUES(868,'compliment','讚賞','It''s a great compliment to be asked to do the job.');
INSERT INTO "toefl" VALUES(869,'notorious','惡名昭彰','The country is notorious for its appalling prison conditions.');
INSERT INTO "toefl" VALUES(870,'inclement','惡劣','inclement weather ');
INSERT INTO "toefl" VALUES(871,'poverty','貧困','Many elderly people live in poverty.');
INSERT INTO "toefl" VALUES(872,'tantalizing','誘人的','The tantalizing aroma of fresh coffee wafted towards them.');
INSERT INTO "toefl" VALUES(873,'submerge','淹沒','The fields had been submerged by floodwater.');
INSERT INTO "toefl" VALUES(874,'minstrel','古音樂家','NULL');
INSERT INTO "toefl" VALUES(875,'quarry','追蹤物','The hunters lost sight of their quarry in the forest.');
INSERT INTO "toefl" VALUES(876,'archive','檔案文件','The BBC''s archives are bulging with material.');
INSERT INTO "toefl" VALUES(877,'ephemeral','短暫的','ephemeral pleasures');
INSERT INTO "toefl" VALUES(878,'deceased','去世的','her deceased parents');
INSERT INTO "toefl" VALUES(879,'scrutiny','檢閱','The documents should be available for public scrutiny.');
INSERT INTO "toefl" VALUES(880,'scenario','腳本','Let me suggest a possible scenario.');
INSERT INTO "toefl" VALUES(881,'Arab','阿拉伯人','NULL');
INSERT INTO "toefl" VALUES(882,'eminent','傑出','an eminent architect');
INSERT INTO "toefl" VALUES(883,'Israel','以色列','NULL');
INSERT INTO "toefl" VALUES(884,'heritage','文化遺產','The building is part of our national heritage.');
INSERT INTO "toefl" VALUES(885,'fabricate','編造','The prisoner claimed the police had fabricated his confession.');
INSERT INTO "toefl" VALUES(886,'recruit','招募','They recruited several new members to the club.');
INSERT INTO "toefl" VALUES(887,'foothold','立足點','She edged forward feeling for a foothold.');
INSERT INTO "toefl" VALUES(888,'expedient','權宜之計','The disease was controlled by the simple expedient of not allowing anyone to leave the city.');
INSERT INTO "toefl" VALUES(889,'eradicate','剷除',' We are determined to eradicate racism from our sport.');
INSERT INTO "toefl" VALUES(890,'Kenya','肯亞','NULL');
INSERT INTO "toefl" VALUES(891,'uneasy','不安','His presence made her feel uneasy.');
INSERT INTO "toefl" VALUES(892,'gymnastics','體操','NULL');
INSERT INTO "toefl" VALUES(893,'solicit','招攬','They send representatives abroad to solicit business.');
INSERT INTO "toefl" VALUES(894,'maritime','與海和船有關','the country''s maritime history');
INSERT INTO "toefl" VALUES(895,'consecutive','連續的','She was absent for nine consecutive days.');
INSERT INTO "toefl" VALUES(896,'Iraq','伊拉克','NULL');
INSERT INTO "toefl" VALUES(897,'swoop','俯衝','A hawk swooped low over the field.');
INSERT INTO "toefl" VALUES(898,'Syria','敘利亞','NULL');
INSERT INTO "toefl" VALUES(899,'nocturnal','夜行性的','NULL');
INSERT INTO "toefl" VALUES(900,'basement','地下室','NULL');
INSERT INTO "toefl" VALUES(901,'antique','骨董級的','an antique mahogany desk');
INSERT INTO "toefl" VALUES(902,'rub','摩擦','She rubbed her chin thoughtfully.');
INSERT INTO "toefl" VALUES(903,'rug','地毯','a sheepskin rug');
INSERT INTO "toefl" VALUES(904,'reed','蘆葦','The edge of the lake was fringed with reeds.');
INSERT INTO "toefl" VALUES(905,'competent','可勝任的','He''s very competent in his work.');
INSERT INTO "toefl" VALUES(906,'aerobic','有氧的','aerobic bacteria');
INSERT INTO "toefl" VALUES(907,'tribute','貢獻','His recovery is a tribute to the doctors'' skill.');
INSERT INTO "toefl" VALUES(908,'discharge','排放',' The river is diverted through the power station before discharging into the sea.');
INSERT INTO "toefl" VALUES(909,'apparatus','(器官)系統','the sensory apparatus');
INSERT INTO "toefl" VALUES(910,'would-be','想成為..的人','advice for would-be parents');
INSERT INTO "toefl" VALUES(911,'hardwood','闊葉木材','Environmentalists called for an end to the trade in tropical hardwoods.');
INSERT INTO "toefl" VALUES(912,'antler','鹿角','Poachers in search of antlers prey on red deer.');
INSERT INTO "toefl" VALUES(913,'warrant','權證','They issued a warrant for her arrest.');
INSERT INTO "toefl" VALUES(914,'impartial','不偏袒','As chairman, I must remain impartial.');
INSERT INTO "toefl" VALUES(915,'neutral','中立的','Journalists are supposed to be politically neutral.');
INSERT INTO "toefl" VALUES(916,'plaque','碑','A bronze plaque marks the house where the poet was born.');
INSERT INTO "toefl" VALUES(917,'cavalry','騎兵','The cavalry charged up the hill to engage the rebels.');
INSERT INTO "toefl" VALUES(918,'cardboard','硬紙板','a cardboard box');
INSERT INTO "toefl" VALUES(919,'wary','謹慎的','She was wary of getting involved with him.');
INSERT INTO "toefl" VALUES(920,'idiosyncrasy','特性','Wearing a raincoat, even on a hot day, is one of her idiosyncrasies.');
INSERT INTO "toefl" VALUES(921,'bestow','賜予','It was a title bestowed upon him by the king.');
INSERT INTO "toefl" VALUES(922,'digress','離題','After several digressions, he finally got to the point.');
INSERT INTO "toefl" VALUES(923,'constrict','限制','Film-makers of the time were constricted by the censors.');
INSERT INTO "toefl" VALUES(924,'Brazil','巴西','NULL');
INSERT INTO "toefl" VALUES(925,'preordain','注定','the outcome was preordained ');
INSERT INTO "toefl" VALUES(926,'underscore','畫底線','The names of the winners are underlined in red.');
INSERT INTO "toefl" VALUES(927,'agile','靈活的','a strong and agile athlete');
INSERT INTO "toefl" VALUES(928,'squat','蹲','Children were squatting on the floor.');
INSERT INTO "toefl" VALUES(929,'upland','山地','NULL');
INSERT INTO "toefl" VALUES(930,'ubiquitous','普遍的','the ubiquitous bicycles of university towns');
INSERT INTO "toefl" VALUES(931,'Helios','太陽神','NULL');
INSERT INTO "toefl" VALUES(932,'arthropod','節肢動物','NULL');
INSERT INTO "toefl" VALUES(933,'serene','幽靜的','a lake, still and serene in the sunlight');
INSERT INTO "toefl" VALUES(934,'minuscule','微小的','minuscule handwriting');
INSERT INTO "toefl" VALUES(935,'escalate','抬升','We do not want to escalate the war.');
INSERT INTO "toefl" VALUES(936,'curate','策畫(展覽品)','He curated the acclaimed ‘Africa’ exhibition at the museum last year.');
INSERT INTO "toefl" VALUES(937,'coarse','粗的(沙)','coarse sand');
INSERT INTO "toefl" VALUES(938,'detour','繞道(N)','We had to make a detour around the flooded fields.');
INSERT INTO "toefl" VALUES(939,'onset','起始','the onset of disease');
INSERT INTO "toefl" VALUES(940,'smother','濃煙','NULL');
INSERT INTO "toefl" VALUES(941,'anonymous','匿名的','The money was donated by a local businessman who wishes to remain anonymous.');
INSERT INTO "toefl" VALUES(942,'Greco-Roman','希臘羅馬式','NULL');
INSERT INTO "toefl" VALUES(943,'curb','抑制','A range of policies have been introduced aimed at curbing inflation.');
INSERT INTO "toefl" VALUES(944,'deduce','下結論','We can deduce a lot from what people choose to buy.');
INSERT INTO "toefl" VALUES(945,'bode','預示','These figures do not bode well for the company''s future.');
INSERT INTO "toefl" VALUES(946,'mindset','心態','a conservative mindset');
INSERT INTO "toefl" VALUES(947,'thatch','稻草屋頂','The thatch was badly damaged in the storm.');
INSERT INTO "toefl" VALUES(948,'contemplate','思考','He continued while she contemplated how to answer.');
INSERT INTO "toefl" VALUES(949,'linen','亞麻布','NULL');
INSERT INTO "toefl" VALUES(950,'thereafter','在那之後','She married at 17 and gave birth to her first child shortly thereafter.');
INSERT INTO "toefl" VALUES(951,'Hamlet','哈姆雷特','NULL');
INSERT INTO "toefl" VALUES(952,'equilibrium','平衡','Any disturbance to the body''s state of equilibrium can produce stress.');
INSERT INTO "toefl" VALUES(953,'repercussion','餘波','The collapse of the company will have repercussions for the whole industry.');
INSERT INTO "toefl" VALUES(954,'emigrate','移民','The family left Czechoslovakia in 1968 and emigrated to America.');
INSERT INTO "toefl" VALUES(955,'versatile','多才多藝的','He''s a versatile actor who has played a wide variety of parts.');
INSERT INTO "toefl" VALUES(956,'anemia','貧血','NULL');
INSERT INTO "toefl" VALUES(957,'manure','肥料','Dig plenty of well-rotted manure into the soil.');
INSERT INTO "toefl" VALUES(958,'enlighten','開導','She didn''t enlighten him about her background.');
INSERT INTO "toefl" VALUES(959,'disposition','性格','people of a nervous disposition');
INSERT INTO "toefl" VALUES(960,'adverse','負面的','This drug is known to have adverse side effects.');
INSERT INTO "toefl" VALUES(961,'livelihood','生計','Communities on the island depended on whaling for their livelihood.');
INSERT INTO "toefl" VALUES(962,'clergy','神職人員','All the local clergy were asked to attend the ceremony.');
INSERT INTO "toefl" VALUES(963,'ferry','渡輪','NULL');
INSERT INTO "toefl" VALUES(964,'bustle','奔忙','She bustled around in the kitchen.');
INSERT INTO "toefl" VALUES(965,'refuge','避難所','He regarded the room as a refuge from the outside world.');
INSERT INTO "toefl" VALUES(966,'assortment','種類','He was dressed in an odd assortment of clothes.');
INSERT INTO "toefl" VALUES(967,'temperament','天性','She''s a dreamer and a romantic by temperament.');
INSERT INTO "toefl" VALUES(968,'perch','坐在(邊邊)','A robin was perching on the fence.');
INSERT INTO "toefl" VALUES(969,'aluminum','鋁','NULL');
INSERT INTO "toefl" VALUES(970,'Broadway','百老匯','The play opened on Broadway in 2008.');
INSERT INTO "toefl" VALUES(971,'comb','梳子','NULL');
INSERT INTO "toefl" VALUES(972,'clutter','填滿(髒亂)','I don''t want all these files cluttering up my desk.');
INSERT INTO "toefl" VALUES(973,'modem','數據機','NULL');
INSERT INTO "toefl" VALUES(974,'excrete','排泄','When someone is diabetic, they excrete sugar in their urine.');
INSERT INTO "toefl" VALUES(975,'paddy','稻田','a rice paddy');
INSERT INTO "toefl" VALUES(976,'wield','舞動','She wields enormous power within the party.');
INSERT INTO "toefl" VALUES(977,'ambiguous','曖昧的','Her account was deliberately ambiguous');
INSERT INTO "toefl" VALUES(978,'bout','短期','Regular exercise is better than occasional bouts of strenuous activity.');
INSERT INTO "toefl" VALUES(979,'sidewalk','人行道','NULL');
INSERT INTO "toefl" VALUES(980,'backfire','失敗','Unfortunately the plan backfired.');
INSERT INTO "toefl" VALUES(981,'albeit','雖然','He finally agreed, albeit reluctantly, to help us.');
INSERT INTO "toefl" VALUES(982,'knack','訣竅','It''s easy, once you've got the knack.');
INSERT INTO "toefl" VALUES(983,'hallmark','跡象','Police said the explosion bore all the hallmarks of a terrorist attack.');
INSERT INTO "toefl" VALUES(984,'crane','鶴','NULL');
INSERT INTO "toefl" VALUES(985,'junior','大三','I spent my junior year in France.');
INSERT INTO "toefl" VALUES(986,'feast','盛宴','The evening was a real feast for music lovers.');
INSERT INTO "toefl" VALUES(987,'jot','速寫','I''ll just jot down the address for you.');
INSERT INTO "toefl" VALUES(988,'nickel','鎳','NULL');
INSERT INTO "toefl" VALUES(989,'Inca','印加帝國','NULL');
INSERT INTO "toefl" VALUES(990,'sporadic','不定期的','sporadic outbreaks of the disease');
INSERT INTO "toefl" VALUES(991,'linger','殘留','The civil war lingered on well into the 1930s.');
INSERT INTO "toefl" VALUES(992,'counteract','反制','These exercises aim to counteract the effects of stress and tension.');
INSERT INTO "toefl" VALUES(993,'cliff','懸崖','We set off along the cliff path.');
INSERT INTO "toefl" VALUES(994,'ignite','點燃','Flames melted a lead pipe and ignited leaking gas.');
INSERT INTO "toefl" VALUES(995,'heterogeneous','大雜燴的','the heterogeneous population of the United States');
INSERT INTO "toefl" VALUES(996,'rebellion','革命','The army put down the rebellion.');
INSERT INTO "toefl" VALUES(997,'haphazard','雜亂無章的','The books had been piled on the shelves in a haphazard fashion.');
INSERT INTO "toefl" VALUES(998,'notwithstanding','儘管','Notwithstanding some major financial problems, the school has had a successful year.');
INSERT INTO "toefl" VALUES(999,'embark','上船','We stood on the pier and watched as they embarked.');
INSERT INTO "toefl" VALUES(1000,'regimen','養生之道','a daily regimen of exercise');
INSERT INTO "toefl" VALUES(1001,'avid','熱切的','She has taken an avid interest in the project.');
INSERT INTO "toefl" VALUES(1002,'trauma','創傷','The children showed no signs of trauma after their ordeal.');
INSERT INTO "toefl" VALUES(1003,'tactual','觸覺的','NULL');
INSERT INTO "toefl" VALUES(1004,'extant','還存在的','A limited number of documents from the period are still extant.');
INSERT INTO "toefl" VALUES(1005,'teem','下大(雨)','It was teeming with rain.');
INSERT INTO "toefl" VALUES(1006,'antiseptic','消毒水','Use antiseptic to clean and dress cuts.');
INSERT INTO "toefl" VALUES(1007,'chisel','鑿刀','NULL');
INSERT INTO "toefl" VALUES(1008,'pinnacle','巔峰','He spent more than twenty years at the pinnacle of his profession.');
INSERT INTO "toefl" VALUES(1009,'sumptuous','高檔的','We dined in sumptuous surroundings.');
INSERT INTO "toefl" VALUES(1010,'inauspicious','不詳的','an inauspicious start');
INSERT INTO "toefl" VALUES(1011,'exude','滲出',' The plant exudes a sticky fluid.');
INSERT INTO "toefl" VALUES(1012,'dainty','優雅的','She took a dainty little bite of the apple.');
INSERT INTO "toefl" VALUES(1013,'procure','取得','They procured a copy of the report for us.');
INSERT INTO "toefl" VALUES(1014,'countervail','抵銷','NULL');
INSERT INTO "toefl" VALUES(1015,'disband','解散','They set about disbanding the terrorist groups.');
INSERT INTO "toefl" VALUES(1016,'scorn','輕藐','She was unable to hide the scorn in her voice.');
INSERT INTO "toefl" VALUES(1017,'antagonist','反對者','He has always been the prime minister''s most formidable antagonist in Parliament.');
INSERT INTO "toefl" VALUES(1018,'stagger','蹣跚','We seem to stagger from one crisis to the next.');
INSERT INTO "toefl" VALUES(1019,'plumage','羽毛','to be in summer/winter plumage');
INSERT INTO "toefl" VALUES(1020,'scorch','燙焦','I scorched my dress when I was ironing it.');
INSERT INTO "toefl" VALUES(1021,'beckon','招手','He beckoned to the waiter to bring the bill.');
INSERT INTO "toefl" VALUES(1022,'hasty','匆促的','Let''s not make any hasty decisions.');
INSERT INTO "toefl" VALUES(1023,'hamper','阻礙','Our efforts were severely hampered by a lack of money.');
INSERT INTO "toefl" VALUES(1024,'roundabout','圓環','When entering a roundabout, give way to any traffic already on it.');
INSERT INTO "toefl" VALUES(1025,'swell','腫脹','Bacteria can cause gums to swell and bleed.');
INSERT INTO "toefl" VALUES(1026,'stringent','緊縮','the government''s stringent economic policies');
INSERT INTO "toefl" VALUES(1027,'extol','讚頌','Doctors often extol the virtues of eating less fat.');
INSERT INTO "toefl" VALUES(1028,'cherish','珍惜','Children need to be cherished.');
INSERT INTO "toefl" VALUES(1029,'boon','福音','The new software will prove a boon to Internet users.');
INSERT INTO "toefl" VALUES(1030,'vagary','千變萬化','the vagaries of weather');
INSERT INTO "toefl" VALUES(1031,'formidable','不容小覷的','She has a formidable list of qualifications.');
INSERT INTO "toefl" VALUES(1032,'havoc','浩劫','The floods caused havoc throughout the area.');
INSERT INTO "toefl" VALUES(1033,'majestic','雄偉的','The Rockies are majestic in size.');
INSERT INTO "toefl" VALUES(1034,'abort','早產','The virus can cause pregnant animals to abort.');
INSERT INTO "toefl" VALUES(1035,'contrive','力圖','Somehow they contrived to live on her tiny income.');
INSERT INTO "toefl" VALUES(1036,'supplant','取代','Their work has been largely supplanted by the use of a computer program that fulfils the same function.');
INSERT INTO "toefl" VALUES(1037,'jolt','顛簸','The plane landed with a jolt.');
INSERT INTO "toefl" VALUES(1038,'vial','小藥瓶','NULL');
INSERT INTO "toefl" VALUES(1039,'groundwork','前置作業','Officials are laying the groundwork for a summit conference of world leaders.');
INSERT INTO "toefl" VALUES(1040,'circuitous','迂迴的','He took us on a circuitous route to the hotel.');
INSERT INTO "toefl" VALUES(1041,'inert','沒幹勁的','The president has to operate within an inert political system.');
INSERT INTO "toefl" VALUES(1042,'dangle','擺盪','She dangled her car keys nervously as she spoke.');
INSERT INTO "toefl" VALUES(1043,'staunch','忠貞的','one of the president''s staunchest allies');
INSERT INTO "toefl" VALUES(1044,'anarchy','無政府狀態','The overthrow of the military regime was followed by a period of anarchy.');
INSERT INTO "toefl" VALUES(1045,'tenet','宗旨','one of the basic/central tenets of Christianity');
INSERT INTO "toefl" VALUES(1046,'deluxe','高檔的','The de luxe edition is bound in leather.');
INSERT INTO "toefl" VALUES(1047,'astute','精明的','It was an astute move to sell the shares then.');
INSERT INTO "toefl" VALUES(1048,'inflate','充氣','The balloons had been inflated with helium.');
INSERT INTO "toefl" VALUES(1049,'burgeon','蓬勃發展','The Vietnam anti-war movement began to burgeon in 1965.');
INSERT INTO "toefl" VALUES(1050,'aggravate','加重','Pollution can aggravate asthma.');
INSERT INTO "toefl" VALUES(1051,'annihilate','摧毀','The human race has enough weapons to annihilate itself.');
INSERT INTO "toefl" VALUES(1052,'pervasive','無所不在的','A sense of social change is pervasive in her novels.');
INSERT INTO "toefl" VALUES(1053,'stride','闊步','We strode across the snowy fields.');
INSERT INTO "toefl" VALUES(1054,'barge','駁船','NULL');
INSERT INTO "toefl" VALUES(1055,'efface','抹除','to efface one''s unhappy memories. ');
INSERT INTO "toefl" VALUES(1056,'extraneous','無關的','We do not want any extraneous information on the page.');
INSERT INTO "toefl" VALUES(1057,'taper','變窄','The tail tapered to a rounded tip.');
INSERT INTO "toefl" VALUES(1058,'lucrative','可獲利的',' a lucrative business. ');
INSERT INTO "toefl" VALUES(1059,'receptacle','槽','In the backyard there was a large receptacle for catching rainwater.');
INSERT INTO "toefl" VALUES(1060,'pledge','承諾',' Management has given a pledge that there will be no job losses this year.');
INSERT INTO "toefl" VALUES(1061,'concise','精簡的','clear concise instructions');
INSERT INTO "toefl" VALUES(1062,'malleability','延展性','The softness and malleability of gold makes it perfect for making jewellery.');
INSERT INTO "toefl" VALUES(1063,'congeal','凝固','The cold remains of supper had congealed on the plate.');
INSERT INTO "toefl" VALUES(1064,'premise','前提','His reasoning is based on the premise that all people are equally capable of good and evil.');
INSERT INTO "toefl" VALUES(1065,'venue','場地','Please note the change of venue for this event.');
INSERT INTO "toefl" VALUES(1066,'jettison','棄投','to jettison fuel');
INSERT INTO "toefl" VALUES(1067,'predicament','困境','I''m in a terrible predicament.');
INSERT INTO "toefl" VALUES(1068,'unleash','解開','The government''s proposals unleashed a storm of protest in the press.');
INSERT INTO "toefl" VALUES(1069,'inviolable','不可侵犯的','inviolable territory');
INSERT INTO "toefl" VALUES(1070,'tailspin','失控狀態','Following the announcement, share prices went into a tailspin.');
INSERT INTO "toefl" VALUES(1071,'steadfast','堅定的','He remained steadfast in his determination to bring the killers to justice.');
INSERT INTO "toefl" VALUES(1072,'euphoric','愉悅','I was in a state of euphoria all day.');
INSERT INTO "toefl" VALUES(1073,'copious','大量的','She supports her theory with copious evidence.');
INSERT INTO "toefl" VALUES(1074,'parcel','塊地','50 five-acre parcels have already been sold.');
INSERT INTO "toefl" VALUES(1075,'hurdle','關卡(障礙)','The next hurdle will be getting her parents'' agreement.');
INSERT INTO "toefl" VALUES(1076,'stockpile','倉儲','the world''s stockpile of nuclear weapons');
INSERT INTO "toefl" VALUES(1077,'repudiate','否決','Socialism had been repudiated at the polls.');
INSERT INTO "toefl" VALUES(1078,'pare','削去','The training budget has been pared back to a minimum.');
INSERT INTO "toefl" VALUES(1079,'ambivalent','好壞參半的','He has an ambivalent attitude towards her.');
INSERT INTO "toefl" VALUES(1080,'grudge','恩怨','He has a grudge against the world.');
INSERT INTO "toefl" VALUES(1081,'timid','膽怯的','He stopped in the doorway, too timid to go in.');
INSERT INTO "toefl" VALUES(1082,'snap','折','The wind had snapped the tree in two.');
INSERT INTO "toefl" VALUES(1083,'preclude','遏止','Lack of time precludes any further discussion.');
INSERT INTO "toefl" VALUES(1084,'subsidiary','額外的','subsidiary information');
INSERT INTO "toefl" VALUES(1085,'homogeneous','同性質的','a homogeneous group/mixture/population');
INSERT INTO "toefl" VALUES(1086,'ramification','衍伸的後果','These changes are bound to have widespread social ramifications.');
INSERT INTO "toefl" VALUES(1087,'toil','辛勞','Hundreds of men toiled for years at building the pyramid.');
INSERT INTO "toefl" VALUES(1088,'heed','注意聽','They failed to heed the lessons of history.');
INSERT INTO "toefl" VALUES(1089,'inveterate','樂此不疲的','an inveterate liar');
INSERT INTO "toefl" VALUES(1090,'prophecy','預言','She was believed to have the gift of prophecy.');
INSERT INTO "toefl" VALUES(1091,'rupture','破裂','the rupture of a blood vessel');
INSERT INTO "toefl" VALUES(1092,'stylus','觸控筆','NULL');
INSERT INTO "toefl" VALUES(1093,'postulate','假設','They postulated a 500-year lifespan for a plastic container.');
INSERT INTO "toefl" VALUES(1094,'aberrant','不被世人接受的','aberrant behaviour');
INSERT INTO "toefl" VALUES(1095,'prowess','卓爾不群','He was complimented on his prowess as an oarsman.');
INSERT INTO "toefl" VALUES(1096,'cardinal','主教','Cardinal Brady');
INSERT INTO "toefl" VALUES(1097,'seething','沸騰','The resort is seething with tourists all year round.');
INSERT INTO "toefl" VALUES(1098,'showcase','大展身手的契機','The festival was a showcase for young musicians.');
INSERT INTO "toefl" VALUES(1099,'loam','肥土','NULL');
